[Refactor] Introduce flint-data for models and interfaces
opensearch-project/opensearch-spark pull request #373
Opened 2024-06-10 07:10 UTC by noCharger

### Description
* [Refactor] Introduce flint-data for models and interfaces

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-10 16:03 UTC, ykmr1224 requested changes

2024-06-10 16:29 UTC, dai-chen commented on flint-data/src/main/scala/org/opensearch/flint/data/ContextualData.scala
> +trait ContextualData {
+1 Could you share more context in PR description or Scaladoc for this new module and main interfaces? For now, it seems not very clear why `FlintCommand` + `FlintInstance` = `fint-data`.

2024-06-10 20:29 UTC, noCharger commented on flint-data/src/main/scala/org/opensearch/flint/data/ContextualData.scala
> +  var context: Map[String, Any] = Map.empty
The map assignment is required during the flintInstance initialization.

2024-06-10 21:22 UTC, noCharger commented on flint-data/src/main/scala/org/opensearch/flint/data/FlintInstance.scala
> +      s"lastUpdateTime=$lastUpdateTime, jobStartTime=$jobStartTime, excludedJobIds=$excludedJobIdsStr, error=$errorStr, context=$context)"
removed context from toString

2024-06-10 21:35 UTC, noCharger commented on flint-data/src/main/scala/org/opensearch/flint/data/ContextualData.scala
> +trait ContextualData {
Good point, so the long term goal is to refactor current entry point. Will create an RFC later.

2024-06-11 18:25 UTC, ykmr1224 commented on flint-data/src/main/scala/org/opensearch/flint/data/ContextualData.scala
> +   */
Let's try not to add redundant comment. The best state is the code explaining by itself without comment. Reference: https://gist.github.com/wojteklu/73c6914cc446146b8b533c0988cf8d29#comments-rules

2024-06-11 18:29 UTC, vamsi-amazon commented on flint-data/src/main/scala/org/opensearch/flint/data/ContextualData.scala
> +  def addContext(key: String, value: Any): Unit = {
context is map right...this method is adding a key value pair to the context..`addContext` is giving a wrong impression of adding entire map. Am I getting this correct?

2024-06-11 18:30 UTC, vamsi-amazon commented on flint-data/src/main/scala/org/opensearch/flint/data/FlintCommand.scala
> +object CommandStates {
Is FlintCommand statement? Just trying to understanding why are we using different nomenclature in sql plugin and spark repo.

2024-06-11 18:31 UTC, vamsi-amazon commented on flint-data/src/main/scala/org/opensearch/flint/data/FlintCommand.scala
>  class FlintCommand(
Can we change this to FlintStatement? If it is a big change ignore.

2024-06-11 18:33 UTC, dai-chen commented
Just read issue https://github.com/opensearch-project/opensearch-spark/issues/376 for context.
IMHO, `flint-data` is confusing and not sure what we plan to put into this module in future.
Any better name? At the moment, the module is more like Flint session model?

2024-06-11 18:36 UTC, vamsi-amazon commented on flint-data/src/main/scala/org/opensearch/flint/data/ContextualData.scala
> +trait ContextualData {
ContextualData looks like a POJO model. ContextualDataStore or ContextDataStore or ContextValueStore would be better trait names.

2024-06-11 18:39 UTC, vamsi-amazon commented on build.sbt
> +  .aggregate(flintData, flintCore, flintSparkIntegration, pplSparkIntegration, sparkSqlApplication, integtest)
What is the reason behind naming flintData?

2024-06-11 19:05 UTC, noCharger commented
> Just read issue #376 for context. IMHO, `flint-data` is confusing and not sure what we plan to put into this module in future. Any better name? At the moment, the module is more like Flint session model?

@dai-chen The primary goal is to provide a shared library that allows for easier extension. So maybe `flint-common` or `flint-utils`, any suggestions?

2024-06-11 19:46 UTC, vamsi-amazon commented
> > Just read issue #376 for context. IMHO, `flint-data` is confusing and not sure what we plan to put into this module in future. Any better name? At the moment, the module is more like Flint session model?
> 
> > What is the rationale behind naming flintData? It seems to suggest to have all the related model classes, but it does have behavior classes.
> 
> @dai-chen @vamsi-amazon The primary goal is to provide a shared library that allows for easier extension. So maybe `flint-common` or `flint-utils`, any suggestions?

flint-commons can be a good name....but we need to define what the responsibility of the module.

2024-06-11 20:05 UTC, noCharger commented
> > > Just read issue #376 for context. IMHO, `flint-data` is confusing and not sure what we plan to put into this module in future. Any better name? At the moment, the module is more like Flint session model?
> > 
> > 
> > > What is the rationale behind naming flintData? It seems to suggest to have all the related model classes, but it does have behavior classes.
> > 
> > 
> > @dai-chen @vamsi-amazon The primary goal is to provide a shared library that allows for easier extension. So maybe `flint-common` or `flint-utils`, any suggestions?
> 
> flint-commons can be a good name....but we need to define what the responsibility of the module.

Thanks, update the responsibility in readme

2024-06-11 21:06 UTC, dai-chen approved these changes

2024-06-12 15:01 UTC, merged