Add percentile PPL function
opensearch-project/opensearch-spark pull request #547
Opened 2024-08-09 16:58 UTC by salyh

### Description
This PR implements the percentile PPL stats function

### Issues Resolved
https://github.com/opensearch-project/opensearch-spark/issues/482

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-08-09 17:15 UTC, salyh commented
Should we also add PERCENTILE_APPROX? Would be a nobrainer imho.

2024-08-09 17:17 UTC, salyh commented
Am I right that the percentileAggFunction https://github.com/eliatra/opensearch-spark/blob/percentile/ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4#L244 is something out of scope with regards to this PR?

2024-08-09 17:18 UTC, salyh commented
Seems I missed https://github.com/opensearch-project/sql/blob/main/ppl/src/main/antlr/OpenSearchPPLParser.g4#L241C1-L244C5  althoug not sure what "compression" refers to?

2024-08-09 17:46 UTC, YANG-DB requested changes

2024-08-09 17:46 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/AggregatorTranslator.java
> +            case PERCENTILE:
@salyh please add logical plan tests and full query IT tests

2024-08-14 05:19 UTC, kt-eliatra commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/AggregatorTranslator.java
> +            case PERCENTILE:
done

2024-08-16 19:42 UTC, YANG-DB reviewed
Thanks
please add sample usage in the [README section](https://github.com/opensearch-project/opensearch-spark/blob/c733d3cb403e5e57c2c2c4625be7ec5ce8c8ff10/ppl-spark-integration/README.md?plain=1#L260)

2024-08-16 20:43 UTC, YANG-DB commented
Regarding `percentileAggFunction` you are correct - this command is no longer in the [SQL PPL antlr](https://github.com/opensearch-project/sql/blob/main/ppl/src/main/antlr/OpenSearchPPLParser.g4)

2024-08-18 15:23 UTC, salyh commented
> Thanks please add sample usage in the [README section](https://github.com/opensearch-project/opensearch-spark/blob/c733d3cb403e5e57c2c2c4625be7ec5ce8c8ff10/ppl-spark-integration/README.md?plain=1#L260)

can you pls first comment on:

- https://github.com/opensearch-project/opensearch-spark/pull/547#issuecomment-2278393281
- https://github.com/opensearch-project/opensearch-spark/pull/547#issuecomment-2278397379

2024-08-18 21:10 UTC, YANG-DB approved these changes

2024-08-20 21:55 UTC, merged