Fix distinct_count ppl stats function
opensearch-project/opensearch-spark pull request #548
Opened 2024-08-09 17:00 UTC by salyh

### Description
Fix distinct_count ppl stats function
Add test for distinct_count

### Issues Resolved
https://github.com/opensearch-project/opensearch-spark/issues/484

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-08-09 17:47 UTC, YANG-DB requested changes

2024-08-09 17:47 UTC, YANG-DB commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
> +  test("create ppl simple country distinct_count ") {
@salyh please add logical plan tests and additional  IT tests with a combination of multiple commands in the same statement

2024-08-13 07:48 UTC, kt-eliatra commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
> +  test("create ppl simple country distinct_count ") {
done

2024-08-15 16:23 UTC, YANG-DB commented
please also add the command description in the readme section at the last part of the [page](https://github.com/opensearch-project/opensearch-spark/blob/main/ppl-spark-integration/README.md)

2024-08-15 19:46 UTC, YANG-DB commented
hi
plz also run ` sbt scalafmtAll  ` ...

2024-08-16 20:05 UTC, YANG-DB reviewed
please also add the command description in the readme section at the last part of the [page](https://github.com/opensearch-project/opensearch-spark/blob/main/ppl-spark-integration/README.md)

2024-08-16 20:05 UTC, YANG-DB commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationWithSpanITSuite.scala
> +    assert(compareByString(expectedPlan) === compareByString(logicalPlan))
replace with `comparePlans(expectedPlan, logPlan, false)` from `PlanTest` as shown here:
```
class PPLLogicalPlanBasicQueriesTranslatorTestSuite
    extends SparkFunSuite
    with PlanTest
    with LogicalPlanTestUtils
    with Matchers {
```

2024-08-16 20:05 UTC, YANG-DB commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
> +    assert(
replace with `comparePlans(expectedPlan, logPlan, false)` from `PlanTest` as shown here:
```
class PPLLogicalPlanBasicQueriesTranslatorTestSuite
    extends SparkFunSuite
    with PlanTest
    with LogicalPlanTestUtils
    with Matchers {
```

2024-08-18 15:29 UTC, salyh commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationWithSpanITSuite.scala
> +    assert(compareByString(expectedPlan) === compareByString(logicalPlan))
done

2024-08-18 15:29 UTC, salyh commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
> +    assert(
done

2024-08-18 21:08 UTC, YANG-DB commented
Please fix [DCO](https://github.com/opensearch-project/opensearch-spark/actions/runs/10441721128/job/28913200848?pr=548) (signOff commits)

2024-08-19 06:15 UTC, kt-eliatra commented
> Please fix [DCO](https://github.com/opensearch-project/opensearch-spark/actions/runs/10441721128/job/28913200848?pr=548) (signOff commits)

it should be OK now

2024-08-20 16:33 UTC, YANG-DB approved these changes

2024-08-21 16:07 UTC, YANG-DB approved these changes

2024-08-21 16:07 UTC, merged