Implement stddev_samp and stddev_pop ppl stats function
opensearch-project/opensearch-spark pull request #549
Opened 2024-08-09 17:06 UTC by salyh

### Description
Implement stddev_samp and stddev_pop ppl stats function

### Issues Resolved
https://github.com/opensearch-project/opensearch-spark/issues/483

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-08-09 17:35 UTC, YANG-DB requested changes

2024-08-09 17:35 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/AggregatorTranslator.java
> +            case STDDEV_POP:
@salyh please add logical plan tests and full query IT tests

2024-08-09 17:35 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/AggregatorTranslator.java
> +            case STDDEV_SAMP:
@salyh please add logical plan tests and full query IT tests

2024-08-14 09:21 UTC, kt-eliatra commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/AggregatorTranslator.java
> +            case STDDEV_SAMP:
done

2024-08-15 16:18 UTC, YANG-DB reviewed
looks good
please also add the command description in the readme section at the last part of the [page](https://github.com/opensearch-project/opensearch-spark/blob/main/ppl-spark-integration/README.md)

2024-08-15 19:44 UTC, YANG-DB commented
hi
plz also run ` sbt scalafmtAll  ` for solving the [failed CI / build](https://github.com/opensearch-project/opensearch-spark/actions/runs/10384781425/job/28820984141?pr=549#step:5:28)

2024-08-15 19:45 UTC, YANG-DB commented
hi
plz also run ` sbt scalafmtAll  ` for solving the [failed CI / build](https://github.com/opensearch-project/opensearch-spark/actions/runs/10384781425/job/28820984141?pr=549#step:5:28)

2024-08-18 21:03 UTC, YANG-DB approved these changes

2024-08-20 17:54 UTC, merged