Implementation of case function.
opensearch-project/opensearch-spark pull request #695
Opened 2024-09-24 21:27 UTC by lukasz-soszynski-eliatra

### Description
Implementation of the `case` function

### Issues Resolved
https://github.com/opensearch-project/opensearch-spark/issues/645

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-09-25 05:49 UTC, YANG-DB requested changes

2024-09-25 05:49 UTC, YANG-DB commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLEvalITSuite.scala
> +  test("eval case function") {
Can you also add more complex tests use case including composition of additional commands such as where conditions and stats ?
thanks

2024-09-25 05:49 UTC, YANG-DB commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFiltersITSuite.scala
> +  test("case function used as filter") {
can u also add here some additional tests use cases of more complicated composition ppl commands ?

2024-09-25 05:49 UTC, YANG-DB commented on ppl-spark-integration/README.md
> +   ```
plz add more examples for using case in other use cases that include where clause / stats commands

2024-09-25 05:49 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
> +  // TODO add case
why is it TODO ?

2024-09-25 11:50 UTC, lukasz-soszynski-eliatra commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
> +  // TODO add case
Good catch. I need to remove this TODO.

2024-09-26 05:03 UTC, YANG-DB commented
@lukasz-soszynski-eliatra  please ping me when this is ready for review
thanks

2024-09-26 08:07 UTC, lukasz-soszynski-eliatra commented
I'll do my best to make corrections today.

2024-09-26 19:35 UTC, lukasz-soszynski-eliatra commented
@YANG-DB 
Please take a look at the [commit](https://github.com/opensearch-project/opensearch-spark/pull/695/commits/5dc26872d4f678e899d978648e99f491bde56828). I added more tests and documentation.

2024-09-26 21:36 UTC, YANG-DB approved these changes

2024-09-27 02:06 UTC, merged

2024-10-28 05:34 UTC, LantaoJin commented
@YANG-DB does this syntax match what we expected? From the issue description, the valid synatx is:
```
CASE(<predicate1>, <value1>, [<predicate2>, <value2>, ...] [ELSE] <default>)
```
An valid example:
```
source = my_index
| eval status_category =
    case(status_code >= 200 AND status_code < 300, 'Success',
         status_code >= 300 AND status_code < 400, 'Redirection'
         status_code >= 400 AND status_code < 500, 'Client Error'
         status_code >= 500, 'Server Error',
         'Unknown')
| stats count() by status_category
```

But the implementation we merged is totally different as:
```
CASE(<predicate1>, <value1>[, <predicate2>, <value2>, ...] [ELSE <default>])
```
The example above needs rewritten to
```
source = my_index
| eval status_category =
    case(status_code >= 200 AND status_code < 300, 'Success',
         status_code >= 300 AND status_code < 400, 'Redirection'
         status_code >= 400 AND status_code < 500, 'Client Error'
         status_code >= 500, 'Server Error'
         ELSE 'Unknown')
| stats count() by status_category
```
Note, the `,` after `'Server Error'` is removed and `ELSE` keyword is required for this case.
Please double confirm the current syntax is by designed.