Initial commit for cidr function
opensearch-project/opensearch-spark pull request #706
Opened 2024-09-26 18:50 UTC by salyh

### Description
Implement cidr function to check wether an ip address is with a given cidr

### Issues Resolved
https://github.com/opensearch-project/opensearch-spark/issues/671

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-09-26 18:58 UTC, salyh commented
@YANG-DB @vamshin @anirudha 

I pushed the scaffold for the CIDR function.
The real implementation which validates the ip address and check if its within the cidr is missing because we need to discuss the introduction of a new 3rd party library:

I suggest to add a dependency to https://github.com/seancfoley/IPAddress because this library seems to provide ip validation and in range checking for ipv4 and ipv6 addresses/cidrs. The library is Apache licensed.

Other options are the following libraries or code snippets (or of course manual implementation with java standard library which is error prone in my view):

- https://www.baeldung.com/java-check-ip-address-range
- https://github.com/apache/commons-net (ipv4 only)
- https://github.com/edazdarevic/CIDRUtils/blob/master/CIDRUtils.java (MIT license)

Let me know what you think and what the general process is to discuss new dependencies

2024-09-26 21:38 UTC, YANG-DB commented
Hi @salyh 
I agree - let's use https://github.com/seancfoley/IPAddress library since it's in use in our SQL repo already

2024-09-27 00:14 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/Cidr.java
> +        this.cidrBlock = cidrBlock;
Please merge the latest code base and refactor this class with Lombok annotations. Ref https://github.com/opensearch-project/opensearch-spark/commit/38ca314034021c34765713c016bcf3cef775efab

2024-09-27 00:20 UTC, LantaoJin commented
Hi @salyh 
Can you see if the [Guava library](https://guava.dev/releases/19.0/api/docs/com/google/common/net/InetAddresses.html) can meet our needs?

2024-09-27 09:51 UTC, salyh commented
> Hi @salyh Can you check if the [Guava library](https://guava.dev/releases/19.0/api/docs/com/google/common/net/InetAddresses.html) can meet our needs?

I checked but it does not support cidr checks. https://github.com/seancfoley/IPAddress  is also already used in the sql project.

2024-09-27 09:51 UTC, salyh commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/Cidr.java
> +        this.cidrBlock = cidrBlock;
done

2024-09-27 09:51 UTC, salyh commented
> Hi @salyh I agree - let's use https://github.com/seancfoley/IPAddress library since it's in use in our SQL repo already

done

2024-09-30 04:49 UTC, YANG-DB commented
@salyh plz resolve conflict
thanks

2024-09-30 13:03 UTC, salyh commented
> @salyh plz resolve conflict thanks

done

2024-09-30 13:27 UTC, salyh commented
@YANG-DB @vamshin @anirudha

Regarding validation of the CIDR function parameters:

The [IPAddress](https://github.com/seancfoley/IPAddress) library is very lenient regarding validation of ip addresss and cidr blocks.

I suggest we at least disallow partial ip address segements and empty or null adresses:

```
  IPAddressStringParameters valOptions = new IPAddressStringParameters.Builder()
                .allowEmpty(false)
                .setEmptyAsLoopback(false)
                .allow_inet_aton(false)
                .allowSingleSegment(false)
                .toParams();
```

Then the remaining question is wether we should enforce other syntax checks like which the library is not enforcing:

- check that cidr block is a really a in cicdr notation (containing a '/')
- check that ip address and cidr are either both ipv6 or both ipv4
- define the behaviour for edge cases like 0.0.0.0 (or just rely on the api)
- define handling of special ip adresses like multicast, anycast, 255.*.*.* etc

My suggestion is to only 

- disallow partial ip address segements and empty or null adresses (like already implemented) and leave everything else 
- disallow mixed ipv4/ipv6 adresses and cidr blocks

and leave everything else to the library.

2024-10-07 16:06 UTC, YANG-DB commented
@salyh 
please add the needed documentation in the following locations:
 - [ppl commands list](https://github.com/opensearch-project/opensearch-spark/tree/main/docs/ppl-lang)
 - [ppl functions list](https://github.com/opensearch-project/opensearch-spark/tree/main/docs/ppl-lang/functions)
 - [ppl examples doc](https://github.com/opensearch-project/opensearch-spark/blob/main/docs/ppl-lang/PPL-Example-Commands.md)

2024-10-07 18:24 UTC, YANG-DB commented
> @YANG-DB @vamshin @anirudha
> 
> Regarding validation of the CIDR function parameters:
> 
> The [IPAddress](https://github.com/seancfoley/IPAddress) library is very lenient regarding validation of ip addresss and cidr blocks.
> 
> I suggest we at least disallow partial ip address segements and empty or null adresses:
> 
> ```
>   IPAddressStringParameters valOptions = new IPAddressStringParameters.Builder()
>                 .allowEmpty(false)
>                 .setEmptyAsLoopback(false)
>                 .allow_inet_aton(false)
>                 .allowSingleSegment(false)
>                 .toParams();
> ```
> 
> Then the remaining question is wether we should enforce other syntax checks like which the library is not enforcing:
> 
> * check that cidr block is a really a in cicdr notation (containing a '/')
> * check that ip address and cidr are either both ipv6 or both ipv4
> * define the behaviour for edge cases like 0.0.0.0 (or just rely on the api)
> * define handling of special ip adresses like multicast, anycast, 255._._.* etc
> 
> My suggestion is to only
> 
> * disallow partial ip address segements and empty or null adresses (like already implemented) and leave everything else
> * disallow mixed ipv4/ipv6 adresses and cidr blocks
> 
> and leave everything else to the library.

@salyh 
Thanks for this review - I support your suggestion
- disallow partial ip address segements and empty or null adresses (like already implemented) and leave everything else
- disallow mixed ipv4/ipv6 adresses and cidr blocks

In addition plz document the additional validations as future work:

```
check that cidr block is a really a in cicdr notation (containing a '/')
check that ip address and cidr are either both ipv6 or both ipv4
define the behaviour for edge cases like 0.0.0.0 (or just rely on the api)
define handling of special ip adresses like multicast, anycast, 255...* etc
```
Thanks

2024-10-08 17:14 UTC, YANG-DB reviewed
please add the needed documentation in the following locations:

[ppl planning list](https://github.com/opensearch-project/opensearch-spark/tree/main/docs/ppl-lang/planning)

Once we approve we'll also add it onto the other docs:
 - https://github.com/opensearch-project/opensearch-spark/blob/main/docs/ppl-lang/PPL-Example-Commands.md
 - https://github.com/opensearch-project/opensearch-spark/blob/main/docs/ppl-lang/README.md

2024-10-10 04:10 UTC, penghuo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +            IPAddressString parsedIpAddress = new IPAddressString(ipAddress, valOptions);
Should we leverage [InetAddresses](https://github.com/opensearch-project/OpenSearch/blob/main/libs/common/src/main/java/org/opensearch/common/network/InetAddresses.java) in opensearch-common package to parse IpAddress and CIDR?

2024-10-10 04:10 UTC, penghuo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +                parsedCidrBlock.validate();
Could we align the validation with OpenSearch?

2024-10-10 12:34 UTC, dr-lilienthal commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : CIDR LT_PRTHS ipAddress = functionArg COMMA cidrBlock = functionArg RT_PRTHS
You mean instead of “`where CIDR(src_ip, ‘192.168.0.0/24’)`” that the command “`where CIDRMATCH(src_ip, ‘192.168.0.0/24’)`” is better understandable? Should we change this accordingly?

2024-10-10 12:37 UTC, dr-lilienthal commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +            IPAddressString parsedIpAddress = new IPAddressString(ipAddress, valOptions);
I don't think there's anything wrong with it. It is a well-maintained package

2024-10-11 15:13 UTC, penghuo commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : CIDR LT_PRTHS ipAddress = functionArg COMMA cidrBlock = functionArg RT_PRTHS
yes, should we use cidrmatch instead of cidr as function name.

2024-10-11 15:15 UTC, penghuo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +            IPAddressString parsedIpAddress = new IPAddressString(ipAddress, valOptions);
I am not concerning the package is well-maintained or not.
My point is to be consistent with OpenSearch's parsing and validation behavior.

2024-10-11 16:24 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +                parsedCidrBlock.validate();
@dr-lilienthal I agree with @penghuo 
lets consolidate for using the same functionality
thanks

2024-10-11 16:24 UTC, YANG-DB commented
@dr-lilienthal can u plz resolve the conflicts and also signOff the commits ?( DCO failure )
thanks

2024-10-14 17:19 UTC, salyh commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +                parsedCidrBlock.validate();
When I read this and [the above thread](https://github.com/opensearch-project/opensearch-spark/pull/706#discussion_r1797101977) correct the idea is to remove the https://github.com/seancfoley/IPAddress lib dependency and instead use classes of the `org.opensearch.common.network`, right?

2024-10-14 17:20 UTC, salyh commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +            IPAddressString parsedIpAddress = new IPAddressString(ipAddress, valOptions);
@penghuo Can you provide a link to code or docs where we can see the `OpenSearch's parsing and validation behavior.`?

2024-10-14 17:21 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : CIDR LT_PRTHS ipAddress = functionArg COMMA cidrBlock = functionArg RT_PRTHS
@dr-lilienthal can you rename cidr to cidrmatch?

2024-10-14 19:39 UTC, dr-lilienthal commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : CIDR LT_PRTHS ipAddress = functionArg COMMA cidrBlock = functionArg RT_PRTHS
@salyh yes

2024-10-14 19:57 UTC, dr-lilienthal commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : CIDR LT_PRTHS ipAddress = functionArg COMMA cidrBlock = functionArg RT_PRTHS
done @salyh

2024-10-14 21:10 UTC, penghuo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +            IPAddressString parsedIpAddress = new IPAddressString(ipAddress, valOptions);
https://github.com/opensearch-project/OpenSearch/blob/main/libs/common/src/main/java/org/opensearch/common/network/InetAddresses.java#L358
```
    public static InetAddress forString(String ipString) {
        byte[] addr = ipStringToBytes(ipString);

        // The argument was malformed, i.e. not an IP string literal.
        if (addr == null) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "'%s' is not an IP string literal.", ipString));
        }

        return bytesToInetAddress(addr);
    }
```

2024-10-14 21:11 UTC, penghuo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +                parsedCidrBlock.validate();
Exactally.

2024-10-15 09:46 UTC, salyh commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +            IPAddressString parsedIpAddress = new IPAddressString(ipAddress, valOptions);
@penghuo Thanks. But please see https://github.com/opensearch-project/opensearch-spark/pull/706#discussion_r1800818727

2024-10-24 01:52 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +                parsedCidrBlock.validate();
@penghuo please assist...

2024-10-24 04:07 UTC, penghuo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +                parsedCidrBlock.validate();
@salyh for cidr match, I want to confirm if the behavior of the term query is as expected. If it is, I can help locate the relevant code.
```
GET my-index-000001/_search
{
  "query": {
    "term": {
      "ip_addr": "192.168.0.0/16"
    }
  }
}
```

2024-10-24 12:13 UTC, salyh commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +                parsedCidrBlock.validate();
@penghuo yes it is. Is the relevant code this?: https://github.com/opensearch-project/OpenSearch/blob/119abaff95a7f54affea6c844fad7ce3c8360155/server/src/main/java/org/opensearch/index/mapper/IpFieldMapper.java#L248

If so I try to re-implement based on `org.apache.lucene.document.InetAddressPoint.newPrefixQuery()` which evalutes to something like 

```
byte[] lower = value.getAddress();
    byte[] upper = value.getAddress();
    for (int i = prefixLength; i < 8 * lower.length; i++) {
      int m = 1 << (7 - (i & 7));
      lower[i >> 3] &= ~m;
      upper[i >> 3] |= m;
    }
```

2024-10-25 15:51 UTC, penghuo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +                parsedCidrBlock.validate();
IpField term query is rewritten as PointRangeQuery in lucene. I can think 2 approach
1. read value from child operator, index into Lucene, and run range query.
2. leverage [parseCidr logic](https://github.com/opensearch-project/OpenSearch/blob/main/libs/common/src/main/java/org/opensearch/common/network/InetAddresses.java#L395), and perform match query using https://github.com/seancfoley/IPAddress.

2024-10-28 14:55 UTC, salyh commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +                parsedCidrBlock.validate();
@penghuo @YANG-DB 
I would vote for 2. because 1. is too complex for almost no benefit
But I cannot access `org.opensearch.common.network.InetAddresses` class because its seems not part of the dependencies. While trying to add 'opensearch-commons' lib as dependency i noticed that in build.sbt 

```
lazy val opensearchVersion = "2.6.0"
lazy val opensearchMavenVersion = "2.6.0.0"
```

is set whereas a) the org.opensearch.common.network.InetAddresses was not part of the libarary in this version and b) it seems odd to compile and build against 2.6.0 which is very old

2024-10-28 15:57 UTC, penghuo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +                parsedCidrBlock.validate();
what is the difference of `parsedCidrBlock.validate();` vs OpenSearch implementation? can we leverage `parsedCidrBlock.validate();` now and upgrade later?

2024-10-28 16:32 UTC, salyh commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +                parsedCidrBlock.validate();
sure, thats the easiest way and already implemented. I add tests and check what the differences are ...

2024-10-28 18:30 UTC, YANG-DB requested changes

2024-10-28 18:30 UTC, YANG-DB commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
> +CIDRMATCH:                          'CIDRMATCH';
Add CIDRMATCH to `keywordsCanBeId`

2024-10-28 18:30 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +public class SerializableUdf {
why not use an interface or abstract class in that case  ?

2024-10-28 19:15 UTC, salyh commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +public class SerializableUdf {
Thats imho a pure style discussion. I prefer private constructors because abstract classes are intended for subclassing and interfaces for multiple inheritance. But I am happy to convert it into a abstract class or an interface.

2024-10-28 19:36 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
> +CIDRMATCH:                          'CIDRMATCH';
done

2024-10-28 19:40 UTC, salyh commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +public class SerializableUdf {
Changed to an interface

2024-10-29 17:28 UTC, salyh commented
> @salyh @dr-lilienthal can u plz resolve the conflicts ? thanks

@YANG-DB done

2024-10-29 17:56 UTC, YANG-DB commented on docs/ppl-lang/functions/ppl-ip.md
> + - `ip` can be an IPv4 or an IPv6 address
@salyh please explain 'ip' is a column name and 'cidr' is a literal value

2024-10-29 18:52 UTC, salyh commented on docs/ppl-lang/functions/ppl-ip.md
> + - `ip` can be an IPv4 or an IPv6 address
according to antlr definition its both a `functionArg` (which makes sense imho)

2024-10-29 19:05 UTC, YANG-DB approved these changes

2024-10-30 16:48 UTC, merged