Add PPL Between functionality
opensearch-project/opensearch-spark pull request #758
Opened 2024-10-09 12:19 UTC by dr-lilienthal

### Description
Add PPL Between functionality

### Issues Resolved
https://github.com/opensearch-project/opensearch-spark/issues/679

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-09 16:05 UTC, YANG-DB commented
hi @dr-lilienthal 
plz fix DCO ...

2024-10-11 16:27 UTC, YANG-DB commented
@dr-lilienthal 
please add documentation in the following locations:
- ../docs/ppl-lang/PPL-Example-Commands.md
- ../docs/ppl-lang/README.md
Thanks

2024-10-17 18:26 UTC, dr-lilienthal commented
@YANG-DB ready for review CC: @salyh

2024-10-17 20:08 UTC, YANG-DB approved these changes

2024-10-17 21:55 UTC, YANG-DB requested changes

2024-10-17 21:55 UTC, YANG-DB commented on ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBetweenExpressionTranslatorTestSuite.scala
> +          "source = table | where datetime_field >= '2024-09-10' and datetime_field <= '2024-09-15'"),
hi @dr-lilienthal 
I dont see the `between` phrase here ? what am I missing ?

2024-10-18 09:18 UTC, dr-lilienthal commented on ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBetweenExpressionTranslatorTestSuite.scala
> +          "source = table | where datetime_field >= '2024-09-10' and datetime_field <= '2024-09-15'"),
@YANG-DB have update the test accordingly.

2024-10-24 01:55 UTC, YANG-DB approved these changes

2024-10-25 12:02 UTC, LantaoJin commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
> +BETWEEN:                            'BETWEEN';
Add `BETWEEN` to `keywordsCanBeId`

2024-10-25 12:04 UTC, LantaoJin commented on docs/ppl-lang/PPL-Example-Commands.md
> +- `source = table | where a between 1 and 4`
I think we need explain the range of `between` is [1, 4] rather than (1, 4) in user doc. From the code implementation, I think it is [1, 4]. In anther word, when a = 1, the predicate returns `True`

2024-10-25 12:11 UTC, LantaoJin commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBetweenITSuite.scala
> +  test("test between should return records NOT between two values") {
Can you add two tests (between and not between) with Date/Time in condition?
I think you can use the table by `createTimeSeriesTable`

2024-10-28 04:31 UTC, LantaoJin commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBetweenITSuite.scala
> +  test("test between should return records NOT between two values") {
Please add another test `where age between 20 + 1 and 30 - 1`. There is similar query in TPCH q5: `l_discount between .06 - 0.01 and .06 + 0.01`

2024-10-28 15:54 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   | expr1 = functionArg NOT? BETWEEN expr2 = functionArg AND expr3 = functionArg   # between
I changed this but the syntax also changes from

`where a not between x and y` -> `where not a between x and y` Is this desired?

2024-10-28 16:28 UTC, LantaoJin commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   | expr1 = functionArg NOT? BETWEEN expr2 = functionArg AND expr3 = functionArg   # between
Oh, I see. We can keep the `NOT?` here, and better to add two tests for `a not between` and `not a between`. They should have the same logic evaluation.

2024-10-28 16:32 UTC, LantaoJin commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   | expr1 = functionArg NOT? BETWEEN expr2 = functionArg AND expr3 = functionArg   # between
Actually, just like `IN`, `a not in` is ANSI SQL, but `not a in` is the original design in OpenSearch SQL. So yes, keep the `NOT?` symbol here.

2024-10-28 18:22 UTC, YANG-DB requested changes

2024-10-28 18:22 UTC, YANG-DB commented on docs/ppl-lang/PPL-Example-Commands.md
> +- `source = table | where a between 1 and 4` - Note: This returns a >= 1 and a <= 4, i.e. [1, 4]
@dr-lilienthal please also copy these comments to the `ppl-between.md`

2024-10-28 18:22 UTC, YANG-DB commented on docs/ppl-lang/planning/ppl-between.md
> +2. **Proposed impl**
you can remove the `proposed impl` here since there was no actual discussion about how it should be implemented...

2024-10-28 18:25 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   | expr1 = functionArg NOT? BETWEEN expr2 = functionArg AND expr3 = functionArg   # between
Would have great if can discuss such in the beginning of the PR next time ...

2024-10-28 18:26 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
> +BETWEEN:                            'BETWEEN';
done

2024-10-28 18:26 UTC, salyh commented on docs/ppl-lang/PPL-Example-Commands.md
> +- `source = table | where a between 1 and 4`
done

2024-10-28 18:39 UTC, salyh commented on docs/ppl-lang/planning/ppl-between.md
> +2. **Proposed impl**
done

2024-10-28 18:39 UTC, salyh commented on docs/ppl-lang/PPL-Example-Commands.md
> +- `source = table | where a between 1 and 4` - Note: This returns a >= 1 and a <= 4, i.e. [1, 4]
done

2024-10-28 19:04 UTC, salyh commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBetweenITSuite.scala
> +  test("test between should return records NOT between two values") {
done

2024-10-28 19:05 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   | expr1 = functionArg NOT? BETWEEN expr2 = functionArg AND expr3 = functionArg   # between
done, both "nots" are now supported and are tested

2024-10-29 00:47 UTC, LantaoJin approved these changes
LGTM. Enabled auto-merge when CI passed.

2024-10-29 16:47 UTC, YANG-DB approved these changes

2024-10-29 16:47 UTC, merged