PPL geoip function
opensearch-project/opensearch-spark pull request #781
Opened 2024-10-16 06:18 UTC by salyh

### Description
PPL geoip function

### Issues Resolved
https://github.com/opensearch-project/opensearch-spark/issues/672

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-16 06:20 UTC, salyh commented
@YANG-DB @penghuo @lukasz-soszynski-eliatra @kt-eliatra @dr-lilienthal PPL geoip function syntax proposal

Please review and comment if needed

2024-10-16 16:48 UTC, YANG-DB commented
@LantaoJin @penghuo @dai-chen please add u'r comments here

2024-10-17 07:04 UTC, salyh commented
> @salyh thanks on my end looking good - only question is the `datasource` definition - how does the user creates a new `datasource, can/should the `datasource` be one of the following:
> 
>     * external API
> 
>     * table
> 
>     * file
>       Lets add these capabilities ...

@YANG-DB @LantaoJin @penghuo @dai-chen 

datasource refers to the datasources provided by the ip2geo processor https://opensearch.org/docs/latest/ingest-pipelines/processors/ip2geo/

My idea was to leveage the already present capabilities of the [ip2geo processor](https://opensearch.org/docs/latest/ingest-pipelines/processors/ip2geo/) and extend it as necessary. Because it would avoid code duplication. When I read the docs of the processor correct, GeoLite2 is supported by now. I propose to add the above requested functionality to the processor. Then we try to use the code from the processor (as a library) to solve this issue. Otherwise we would reinvent the wheel.

2024-10-24 07:17 UTC, LantaoJin commented on docs/ppl-lang/planning/ppl-geoip.md
> +### New syntax definition in ANTLR
As a user doc, could we remove the ANTLR related information, what here needs is just a user readable syntax definition.

2024-10-24 07:17 UTC, LantaoJin commented on docs/ppl-lang/planning/ppl-geoip.md
> +### New syntax definition in ANTLR
Oh, the file is located ppl-lang/planning folder. I think we need an user doc instead of design doc. We can copy this design information to the PR description or issue description. And you can easily update your design without any code changes.

2024-10-24 07:17 UTC, LantaoJin commented on docs/ppl-lang/planning/ppl-geoip.md
> +    - `... | eval geoinfo = geoip([datasource,] ipAddress [,properties])`
what does `datasource` mean? Could you use other meaningful usage rather that `abc`? `abc` is not straightforward user case.

2024-10-24 07:17 UTC, LantaoJin commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : GEOIP LT_PRTHS (datasource = functionArg COMMA)? ipAddress = functionArg (COMMA properties = stringLiteral)? RT_PRTHS
> datasource = functionArg

Any case for supporting `functionArg` instead of `stringLiteral`. Again, what does `datasource` mean?

2024-10-24 11:55 UTC, salyh commented on docs/ppl-lang/planning/ppl-geoip.md
> +    - `... | eval geoinfo = geoip([datasource,] ipAddress [,properties])`
datasource refers to the datasources provided by the ip2geo processor, see https://github.com/opensearch-project/opensearch-spark/pull/781#issuecomment-2420675538

2024-10-24 11:56 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : GEOIP LT_PRTHS (datasource = functionArg COMMA)? ipAddress = functionArg (COMMA properties = stringLiteral)? RT_PRTHS
no particular case for `functionArg`. We can change it to `stringLiteral` for sure

datasource refers to the datasources provided by the ip2geo processor, see https://github.com/opensearch-project/opensearch-spark/pull/781#issuecomment-2420675538

2024-10-24 11:58 UTC, salyh commented on docs/ppl-lang/planning/ppl-geoip.md
> +### New syntax definition in ANTLR
@YANG-DB I did unterstand that the `ppl-lang/planning` folder is for design docs. When the design is approved it will be converted to a userdoc and moved out of the `planning` sub-folder. Am I wrong with that assumption?

2024-10-24 13:43 UTC, LantaoJin commented on docs/ppl-lang/planning/ppl-geoip.md
> +### New syntax definition in ANTLR
I thought it was for roadmap. I prefer to using GitHub PR description and comments. It's fine to add design docs in code if you prefer to. But these docs are not for users, we need to write a new one later.

2024-10-25 01:54 UTC, YANG-DB commented on docs/ppl-lang/planning/ppl-geoip.md
> +### New syntax definition in ANTLR
@salyh yes - once design doc is approved we will move it with necessary updates to the regular commands folder

2024-11-04 16:52 UTC, salyh commented
> HI @salyh,
> 
> Currently looking into implementation if this feature. I saw above conversation on planning to leverage ip2geo functionality within geospatial plugin. Did you have a clear idea on how this can be done?
> 
> From my understanding to leverage ip2geo, one must first create a ip2geo processor then attach it to a opensearch pipeline. I am not too sure how the Spark plugin could access this functionality. Some pointers would be much appreciated :)
> 
> Thanks!

The idea is not to leverage the processor as a processor but to reuse its code (either by copying it - not ideal - , or by separating them into a kind of shared commons library or by adding them as a dependency on code level).

2024-11-04 17:04 UTC, kenrickyap commented
Sounds good my current idea is to create an spi for the plugin, as was done for job-scheduler (allowing the geospatial plugin to implement ExtensiblePlugin) am still working on a design. This is to allow the sql plugin to access the ip2geo functionality (am also working on the iplocation functionality there).

Would you know if the Spark project would be able to leverage the SPI since it is not a plugin? If we are to expose the ip2geo functionality I would rather create something that works both for the sql-plugin and Spark.

2024-11-04 20:20 UTC, kenrickyap commented
Hi @salyh, spent a bit more time investigating this ticket. currently plan is to rewrite the geo2ip functionality within the spark project. The reason for this is that currently the geo2ip processor with the geospatial plugin is intwined with using the job scheduler extension. From my understanding there is not way to leverage usage of this extension in spark so a lot of the functionality would not be able to be migrated.

The rewritten geo2ip within spark will:
- create spark temp table storing data from geoip datasource if table does not already exist
- retrieve information from said table based on provided ips.

The current design question is if it would be better to use spark UDF or reflection to call [java_method](https://spark.apache.org/docs/3.5.3/api/sql/index.html#java_method) to call the rewritten geo2ip functionality?

2024-11-05 02:44 UTC, kenrickyap commented
> Hi @salyh, spent a bit more time investigating this ticket. currently plan is to rewrite the geo2ip functionality within the spark project. The reason for this is that currently the geo2ip processor with the geospatial plugin is intwined with using the job scheduler extension. From my understanding there is no way to leverage usage of this extension in spark so a lot of the functionality would not be able to be migrated.
> 
> The rewritten geo2ip within spark will:
> 
> * create spark temp table storing data from geoip datasource if table does not already exist
> * retrieve information from said table based on provided ips.
> 
> The current design question is if it would be better to use spark UDF or reflection to call [java_method](https://spark.apache.org/docs/3.5.3/api/sql/index.html#java_method) to call the rewritten geo2ip functionality?

Will follow CIDR https://github.com/opensearch-project/opensearch-spark/pull/706/files approach and use UDF

2024-11-13 05:15 UTC, YANG-DB requested changes
Only a reference PR - DO NO MERGE !

2024-12-19 23:35 UTC, closed without merging