Flatten
opensearch-project/opensearch-spark pull request #784
Opened 2024-10-16 12:47 UTC by lukasz-soszynski-eliatra

### Description
The `flatten` command is introduced

### Issues Resolved
[_List any issues this PR will resolve, e.g. Closes [...]._ ](https://github.com/opensearch-project/opensearch-spark/issues/669)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-21 19:19 UTC, YANG-DB requested changes

2024-10-22 17:13 UTC, lukasz-soszynski-eliatra commented on docs/ppl-lang/ppl-fillnull-command.md
Sorry, I forgot to commit the file during work on the `fillnull` command. Should I move the file into a dedicated MR?

2024-10-25 10:57 UTC, lukasz-soszynski-eliatra commented on docs/ppl-lang/ppl-fillnull-command.md
Here is MR with the `fillnull` command documentation: https://github.com/opensearch-project/opensearch-spark/pull/815

2024-10-29 18:55 UTC, YANG-DB requested changes

2024-10-29 18:55 UTC, YANG-DB commented on ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanFlattenCommandTranslatorTestSuite.scala
> +  test("test fillnull only field") {
@lukasz-soszynski-eliatra plz change the test name to match the ppl query

2024-10-29 18:55 UTC, YANG-DB commented on ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanFlattenCommandTranslatorTestSuite.scala
@lukasz-soszynski-eliatra plz add more tests with different use cases plz

2024-10-30 02:26 UTC, YANG-DB requested changes

2024-10-30 02:26 UTC, YANG-DB commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFlattenITSuite.scala
> +    createSimpleNestedJsonContentTable(tempFile, testTable)
@lukasz-soszynski-eliatra plz add additional test from other types of tables or use cases:
- [NestesTable](https://github.com/opensearch-project/opensearch-spark/blob/a07f88f86fa384d94e535f99397e8d0d0402bba0/integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala#L511)
- [structTable](https://github.com/opensearch-project/opensearch-spark/blob/a07f88f86fa384d94e535f99397e8d0d0402bba0/integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala#L487)
- table with multiValue column (Array)

2024-10-30 17:43 UTC, YANG-DB commented
@lukasz-soszynski-eliatra also plz rebase ...

2024-10-30 18:46 UTC, lukasz-soszynski-eliatra commented on ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanFlattenCommandTranslatorTestSuite.scala
done

2024-10-30 18:46 UTC, lukasz-soszynski-eliatra commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFlattenITSuite.scala
> +    createSimpleNestedJsonContentTable(tempFile, testTable)
done

2024-10-30 18:47 UTC, lukasz-soszynski-eliatra commented on ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanFlattenCommandTranslatorTestSuite.scala
> +  test("test fillnull only field") {
done

2024-10-30 21:43 UTC, YANG-DB approved these changes

2024-10-31 13:13 UTC, LantaoJin commented on docs/ppl-lang/ppl-flatten-command.md
> +- `array<struct<?,?>>`
Are these data_types what we expecting for this command? I thought the expected input is json string. But it's fine for now. We can enhance it later.

2024-10-31 13:14 UTC, LantaoJin commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
>  commandName
LGTM except this^

2024-10-31 13:19 UTC, lukasz-soszynski-eliatra commented on docs/ppl-lang/ppl-flatten-command.md
> +| 2024-09-13T12:00:00 | [{801, Tower Bridge}, {928, London Bridge}]  | London  | {35, 51.5074, -0.1278} | England       |
These data come from the issue https://github.com/opensearch-project/opensearch-spark/issues/669 but were extended.

2024-10-31 13:35 UTC, lukasz-soszynski-eliatra commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
>  commandName
Corrected.

2024-10-31 18:47 UTC, YANG-DB requested changes

2024-10-31 18:47 UTC, YANG-DB commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
>  commandName
> Please add `FLATTEN` keyword in the end of `commandName` section.
[please add here](https://github.com/opensearch-project/opensearch-spark/blob/0a0e2c5d690839f982fa279ac0f19938e551150b/ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4#L83C12-L84C14)

2024-10-31 19:28 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
>  commandName
done

2024-10-31 20:32 UTC, YANG-DB approved these changes

2024-10-31 20:32 UTC, merged