New trendline ppl command (SMA only)
opensearch-project/opensearch-spark pull request #833
Opened 2024-10-29 21:09 UTC by salyh

### Description
New trendline ppl command (SMA only). For WMA see https://github.com/opensearch-project/opensearch-spark/issues/831

### Related Issues
https://github.com/opensearch-project/opensearch-spark/issues/655

### Check List
- [ ] Updated documentation (docs/ppl-lang/README.md)
- [ ] Implemented unit tests
- [ ] Implemented tests for combination with other commands
- [ ] New added source code should include a copyright header
- [ ] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-29 21:41 UTC, YANG-DB requested changes
Please also add command to the README, a dedicated page for this command with a link to the dedicated doc and examples in the examples page

2024-10-29 21:41 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
> +            .orElse(new Trendline(null, trendlineComputations));
can you use optional instead of null ?

2024-10-29 21:41 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Trendline.java
> +    private final Field sortByField;
this needs to be optional in case of no sort field given

2024-10-29 21:41 UTC, YANG-DB commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   | TRENDLINE
add to `TRENDLINE` to [keywordsCanBeId](https://github.com/opensearch-project/opensearch-spark/blob/cd730cb69b1b7a4f9e9fef6c090f9317a8fd5563/ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4#L1011)

2024-10-30 00:26 UTC, YANG-DB requested changes

2024-10-30 00:26 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
> +        public Expression visitTrendlineComputation(Trendline.TrendlineComputation node, CatalystPlanContext context) {
@salyh can you please extract the content of this method and trendlineOrNullWhenThereAreTooFewDataPoints into a separate TrendlineStrategy class under this [utility package](https://github.com/opensearch-project/opensearch-spark/tree/main/ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils) ? it will simplify this visitor
thanks

2024-10-30 02:13 UTC, LantaoJin commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   | TRENDLINE
@YANG-DB `commandName` set has already added to `keywordsCanBeId`. Not need to add it duplicately.

2024-10-30 11:38 UTC, kt-eliatra commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Trendline.java
> +    private final Field sortByField;
done

2024-10-30 11:38 UTC, kt-eliatra commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
> +            .orElse(new Trendline(null, trendlineComputations));
done

2024-10-30 13:25 UTC, kt-eliatra commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
> +        public Expression visitTrendlineComputation(Trendline.TrendlineComputation node, CatalystPlanContext context) {
done

2024-10-30 13:31 UTC, kt-eliatra commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   | SMA
I'll remove this since it looks like a bug. It was already defined as `trendlineType` here https://github.com/eliatra/opensearch-spark/blob/606c40ef960e9dc4f3fb21aeef5ae4818951167a/ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4#L260

2024-10-30 13:34 UTC, kt-eliatra commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   | SMA
done

2024-10-30 13:45 UTC, kt-eliatra commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : trendlineType LT_PRTHS numberOfDataPoints = integerLiteral COMMA field = fieldExpression RT_PRTHS AS alias = fieldExpression
1. It appeared in all the examples for this issue, that's why it's not optional atm.
2. changed to `qualifiedName`

2024-10-30 14:06 UTC, LantaoJin commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : trendlineType LT_PRTHS numberOfDataPoints = integerLiteral COMMA field = fieldExpression RT_PRTHS AS alias = fieldExpression
Alias should be defined to optional even all examples have aliases. In most case, the trendline command is the last command in pipe, user could ignore to name an alias

2024-10-30 14:07 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   | TRENDLINE
i agree, so nothing to do here

2024-10-30 14:08 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : trendlineType LT_PRTHS numberOfDataPoints = integerLiteral COMMA field = fieldExpression RT_PRTHS AS alias = fieldExpression
@LantaoJin @YANG-DB should we finally make `AS alias = fieldExpression` optional?

2024-10-30 14:52 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : TRENDLINE (SORT sortField)? trendlineClause (trendlineClause)*
@YANG-DB @LantaoJin i think it adds (yet) unneccessary complexity because the use case can also be solved by simply chaining the trendline command

2024-10-30 16:01 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : trendlineType LT_PRTHS numberOfDataPoints = integerLiteral COMMA field = fieldExpression RT_PRTHS AS alias = fieldExpression
ok, will make it optional - what should be the name of the column if alias is omitted? just `trendline`?

2024-10-30 16:18 UTC, YANG-DB commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : TRENDLINE (SORT sortField)? trendlineClause (trendlineClause)*
@LantaoJin - I like this idea but - I agree with @salyh here - lets release this as is for now and once we get any feedback we can revise this command...

2024-10-30 16:28 UTC, YANG-DB approved these changes

2024-10-30 16:40 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : trendlineType LT_PRTHS numberOfDataPoints = integerLiteral COMMA field = fieldExpression RT_PRTHS AS alias = fieldExpression
yes, good idea, @YANG-DB should i add this because you already approved

2024-10-30 16:54 UTC, YANG-DB commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : trendlineType LT_PRTHS numberOfDataPoints = integerLiteral COMMA field = fieldExpression RT_PRTHS AS alias = fieldExpression
yes plz

2024-10-30 16:56 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : trendlineType LT_PRTHS numberOfDataPoints = integerLiteral COMMA field = fieldExpression RT_PRTHS AS alias = fieldExpression
done

2024-10-30 17:41 UTC, YANG-DB requested changes
@salyh plz add logical plan test in the [relevant folder](https://github.com/opensearch-project/opensearch-spark/tree/main/ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl)

2024-10-30 18:29 UTC, salyh commented
> @salyh plz add logical plan test in the [relevant folder](https://github.com/opensearch-project/opensearch-spark/tree/main/ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl) And also plz add a test with no alias example (for logical and actual queries)

done

2024-10-30 18:36 UTC, YANG-DB approved these changes

2024-10-30 19:24 UTC, jduo requested changes

2024-10-30 19:24 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Trendline.java
> +package org.opensearch.sql.ast.tree;
Missing a license header here.

2024-10-30 19:24 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
> +    if (numberOfDataPoints < 0) {
Shouldn't this be < 1? Can't take the average with zero samples.

2024-10-30 19:24 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
> +    String computationType = ctx.trendlineType().getText();
Perhaps this should just evaluate the computation type enum now instead of later.

2024-10-30 19:24 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineStrategy.java
> +package org.opensearch.sql.ppl.utils;
License header needed.

2024-10-30 19:24 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineStrategy.java
> +public interface TrendlineStrategy {
Calling this a Strategy and making it an interface makes it easily confused with the Strategy pattern (where you delegate work to a Strategy interface and the Strategy is changeable at run time).

Suggest renaming to TrendlineCatalystUtils and make it a final @Utility class instead.

2024-10-30 19:24 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineStrategy.java
> +    static List<NamedExpression> visitTrendlineComputations(CatalystQueryPlanVisitor.ExpressionAnalyzer expressionAnalyzer, List<Trendline.TrendlineComputation> computations, CatalystPlanContext cont
The names and parameters of this and visitTrendlineComputation() are similar enough that it is hard to read (and also, this interface isn't a visitor so it might not be appropriate to prefix with "visit").

Suggest getting rid of visitTrendlineComputations, since it's trivial for the caller to do this.
Suggest rename visitTrendlineComputation() to be buildCatalystExpressionFromTrendlineComputation() to help clarity about what the method does.

2024-10-30 19:24 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineStrategy.java
> +        if (node.getComputationType() == Trendline.TrendlineType.SMA) {
Preconditions.checkArgument() here instead?

2024-10-30 21:44 UTC, salyh commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineStrategy.java
> +        if (node.getComputationType() == Trendline.TrendlineType.SMA) {
Not sure what you mean exactly but we will later have more trendline types than only SMA so we need an if or a case statement here.

2024-10-30 21:47 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
> +    if (numberOfDataPoints < 0) {
agree - good point

2024-10-30 21:48 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
> +    String computationType = ctx.trendlineType().getText();
@jduo I don't understand what are you thinking here ? can u plz explain

2024-10-30 21:50 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineStrategy.java
> +    static List<NamedExpression> visitTrendlineComputations(CatalystQueryPlanVisitor.ExpressionAnalyzer expressionAnalyzer, List<Trendline.TrendlineComputation> computations, CatalystPlanContext cont
@jduo I think its an implementation issue - IMO we can keep it as is...

2024-10-30 21:51 UTC, salyh commented on docs/ppl-lang/ppl-trendline-command.md
> +`TRENDLINE [sort <[+|-] sort-field>] SMA(number-of-datapoints, field) [AS alias]`
fixed (sort is imho not a list here)

2024-10-30 21:52 UTC, YANG-DB commented
@jduo thanks for u'r feedback - really appreciated !

2024-10-30 21:53 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
> +    String computationType = ctx.trendlineType().getText();
This builder extracts the trendline computation as a String then passes it as a String to TrendlineComputation's constructor. It might be better to just use TrendlineType.valueOf() at this point rather than pass around the String.

2024-10-30 21:59 UTC, salyh commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineStrategy.java
> +public interface TrendlineStrategy {
I agree to rename it but other util classes in this packages are interfaces, so i vote to keep the interface type

2024-10-30 22:13 UTC, salyh commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
> +    String computationType = ctx.trendlineType().getText();
fixed

2024-10-31 00:41 UTC, LantaoJin commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : TRENDLINE (SORT sortField)? trendlineClause (trendlineClause)*
> @YANG-DB @LantaoJin i think it adds (yet) unneccessary complexity because the use case can also be solved by simply chaining the trendline command

Sure, it brings me that could you add a test to chain multiple trendline commands in IT?

2024-10-31 00:45 UTC, LantaoJin requested changes
https://github.com/opensearch-project/opensearch-spark/pull/833/files#r1823633566

2024-10-31 02:25 UTC, LantaoJin commented
Another question is whether the sort field can be different from the calculated field? If the answer is no, please throw out an exception for `| source = $testTable | trendline sort + name sma(3, age)`.
If the answer is yes, what is the special semantic for above query?

But this `sort` keyword in trendline still seems an one way door design, deep diving we could get another case:
`| source = $testTable | eval age_alias = age | trendline sort + age_alias sma(3, age)`.
Will this query fail either? There is no semantic problem IMO. That's why I comment and suggest [here](https://github.com/opensearch-project/opensearch-spark/pull/833#discussion_r1821772693).

However, I can give an approval to unblock releasing this as is for now as long as [above chaining case](https://github.com/opensearch-project/opensearch-spark/pull/833#pullrequestreview-2406704673) works.

2024-10-31 07:57 UTC, salyh commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : TRENDLINE (SORT sortField)? trendlineClause (trendlineClause)*
added

2024-10-31 07:57 UTC, salyh commented
> https://github.com/opensearch-project/opensearch-spark/pull/833/files#r1823633566
> 
> To save time, you can ignore the plan assertion and just check the return data matching the expectation. Many thanks! Here is an example for chaining `trendline`: `| source = $testTable | eval age_1 = age, age_2 = age | trendline sort - age_1 sma(3, age_1) | trendline sort + age_2 sma(3, age_2)`

@LantaoJin @YANG-DB IT chaining test added

2024-10-31 08:00 UTC, salyh commented
> Another question is whether the sort field can be different from the calculated field? If the answer is no, please throw out an exception for `| source = $testTable | trendline sort + name sma(3, age)`. If the answer is yes, what is the special semantic for above query?
> 
> But this `sort` keyword in trendline still seems an one way door design, deep diving we could get another case: `| source = $testTable | eval age_alias = age | trendline sort + age_alias sma(3, age)`. Will this query fail either? There is no semantic problem IMO. That's why I comment and suggest [here](https://github.com/opensearch-project/opensearch-spark/pull/833#discussion_r1821772693).
> 
> However, I can give an approval to unblock releasing this as is for now as long as [above chaining case](https://github.com/opensearch-project/opensearch-spark/pull/833#pullrequestreview-2406704673) works.

I suggest to return to this when [WMA](https://github.com/opensearch-project/opensearch-spark/issues/831) will be implemented

2024-10-31 18:32 UTC, YANG-DB approved these changes

2024-10-31 19:39 UTC, YANG-DB commented
@salyh plz solve conflicts after recent changes...

2024-10-31 20:20 UTC, salyh commented
> @salyh plz solve conflicts after recent changes...

done

2024-10-31 20:22 UTC, YANG-DB approved these changes

2024-11-01 19:19 UTC, YANG-DB approved these changes

2024-11-01 19:22 UTC, YANG-DB commented
> Another question is whether the sort field can be different from the calculated field? If the answer is no, please throw out an exception for `| source = $testTable | trendline sort + name sma(3, age)`. If the answer is yes, what is the special semantic for above query?
> 
> But this `sort` keyword in trendline still seems an one way door design, deep diving we could get another case: `| source = $testTable | eval age_alias = age | trendline sort + age_alias sma(3, age)`. Will this query fail either? There is no semantic problem IMO. That's why I comment and suggest [here](https://github.com/opensearch-project/opensearch-spark/pull/833#discussion_r1821772693).
> 
> However, I can give an approval to unblock releasing this as is for now as long as [above chaining case](https://github.com/opensearch-project/opensearch-spark/pull/833#pullrequestreview-2406704673) works.

@LantaoJin I'm approving the PR for merge as this issue was addresses [here](https://github.com/opensearch-project/opensearch-spark/blob/ffcc9189a142616dd4a78e9928ecb966401e7c5c/integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLTrendlineITSuite.scala#L217)

2024-11-01 19:22 UTC, merged