Add functions DATE_ADD, DATE_SUB, TIMESTAMPADD, TIMESTAMPDIFF, CURRENT_TIMEZONE and UTC_TIMESTAMP
opensearch-project/opensearch-spark pull request #839
Opened 2024-10-30 09:51 UTC by LantaoJin

### Description
Add functions DATE_ADD, DATE_SUB, TIMESTAMPADD, TIMESTAMPDIFF, CURRENT_TIMEZONE and UTC_TIMESTAMP
Check [docs/ppl-lang/functions/ppl-datetime.md](https://github.com/opensearch-project/opensearch-spark/compare/main...LantaoJin:pr/issues/838?expand=1#diff-8224babfbcfd7f9ff068d35b8df0c401eebb9fc0eccf9c8ba788a7787a821be3) for details.

### Related Issues
Resolves #838 

### Check List
- [ ] Updated documentation (docs/ppl-lang/README.md)
- [ ] Implemented unit tests
- [ ] Implemented tests for combination with other commands
- [ ] New added source code should include a copyright header
- [ ] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-30 14:10 UTC, LantaoJin commented
`DATE_ADD`, `DATE_SUB` are P0 datetime functions, could u have a review? @YANG-DB

2024-10-30 16:13 UTC, YANG-DB requested changes

2024-10-30 16:13 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
> +        private Expression[] createIntervalArgs(IntervalUnit unit, Expression value) {
@LantaoJin can we move this method out to a date/time utility class / interface ?

2024-10-31 01:09 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
> +        private Expression[] createIntervalArgs(IntervalUnit unit, Expression value) {
done

2024-10-31 05:13 UTC, YANG-DB approved these changes

2024-10-31 06:42 UTC, merged