Join side aliases should be optional
opensearch-project/opensearch-spark pull request #862
Opened 2024-11-01 09:01 UTC by LantaoJin

### Description
Imaging a case as following: Assume table1, table2, and table3 all contain a column `id`.
```sql
select
  *
from
  table1 t1,
  table2 t2,
  table3 t3
where
 t1.id = t2.id
 and t1.id = t3.id
```
To rewrite above SQL query to PPL query, we will get
```sql
source = table1
| join left = t1 right = t2 ON t1.id = t2.id table2
| join left = l1 right = t3 ON t1.id = t3.id table3 // <------ issue here! 

The PPL query throws an exception with message:
> `t1`.`id` cannot be resolved, Did you mean one of the following? [`l1`.`id`, `l1`.`id`, `t3`.`id`].

It because the **required left side alias** `l1` overrides the table alias `t1`.

Its logical plan looks
```
'Project [*]
+- 'Filter (('t1.id = 't2.id) AND ('t1.id = 't3.id))
   +- 'Join Inner
      :- 'SubqueryAlias l1  <------ issue root cause
      :  +- 'Join Inner
      :    :- 'SubqueryAlias t1
      :    :  +- 'UnresolvedRelation [table1], [], false
      :    +- 'SubqueryAlias t2
      :       +- 'UnresolvedRelation [table2], [], false
      +- 'SubqueryAlias t3
         +- 'UnresolvedRelation [table3], [], false
```

Check #857 for details

### Related Issues
Resolves #857 

### Check List
- [ ] Updated documentation (docs/ppl-lang/README.md)
- [ ] Implemented unit tests
- [ ] Implemented tests for combination with other commands
- [ ] New added source code should include a copyright header
- [ ] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-11-01 09:11 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java
> -  @Setter @Getter private String alias;
The `alias` in Relation could be removed since we have the `SubqueryAlias` in AST: https://github.com/opensearch-project/opensearch-spark/blob/main/ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/SubqueryAlias.java

Remaining this member causes potential issue if conflicts

2024-11-01 09:11 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java
> -  public List<String> getTableName() {
Never used.

2024-11-01 09:11 UTC, LantaoJin commented on ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanJoinTranslatorTestSuite.scala
> +         | | cross JOIN left = l right = r $testTable4
Comma is optional, I am trying to reduce this usage. But keep the comma won't fail query.

2024-11-01 09:11 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
> +    return ctx.alias != null ? new SubqueryAlias(ctx.alias.getText(), relation) : relation;
We add `SubqueryAlias` ast node instead of adding the alias string into `Relation`.

2024-11-01 09:11 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java
> -  public List<String> getTableName() {
Never used.

2024-11-01 10:03 UTC, LantaoJin commented
Without this fixing, q21 in TPCH couldn't be rewritten to PPL. Link https://github.com/opensearch-project/opensearch-spark/issues/806

2024-11-05 01:55 UTC, YANG-DB requested changes

2024-11-05 01:55 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java
>    private final List<UnresolvedExpression> tableName;
@LantaoJin lates change the name to indicate it may contain multi-part

2024-11-05 01:55 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java
> -  @Setter @Getter private String alias;
@LantaoJin can u give an example for a union query ?
source = a as table_a, b as table_b, c as table_c |  ...

2024-11-05 01:55 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java
> +        isResolvingJoinCondition = true;
can u make this an atomic bool ?

2024-11-05 01:55 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
> +    UnresolvedPlan right;
please add some comment explaining the condition

2024-11-05 06:28 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java
> -  @Setter @Getter private String alias;
> @LantaoJin can u give an example for a union query ? source = a as table_a, b as table_b, c as table_c | ...

No, we didn't support this pattern, see https://github.com/opensearch-project/opensearch-spark/blob/b183b4a297cb6cdb1cdc55b2b7047cad56b63a05/ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4#L323

But we supported the pattern:
`source = table1, table2, table3 as t | where t.name = 'Molly'`
The plan of above is
```
'Union true, true
:- 'Project [*]
:  +- 'Filter ('t.name = Molly)
:     +- 'SubqueryAlias t
:        +- 'UnresolvedRelation [table1], [], false
:- 'Project [*]
:  +- 'Filter ('t.name = Molly)
:     +- 'SubqueryAlias t
:        +- 'UnresolvedRelation [table2], [], false
+- 'Project [*]
   +- 'Filter ('t.name = Molly)
      +- 'SubqueryAlias t
         +- 'UnresolvedRelation [table3], [], false
```

2024-11-05 06:34 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java
>    private final List<UnresolvedExpression> tableName;
done

2024-11-05 06:39 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java
> +        isResolvingJoinCondition = true;
`CatalystPlanContext` is generated by each query. All members in `CatalystPlanContext` should thread-safe.

2024-11-05 06:51 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
> +    UnresolvedPlan right;
done

2024-11-05 17:06 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java
> +        isResolvingJoinCondition = true;
lets add this note on the `CatalystPlanContext` class description for better clarity

2024-11-05 17:07 UTC, YANG-DB approved these changes

2024-11-05 17:07 UTC, YANG-DB commented
@LantaoJin also plz resolve conflicts...

2024-11-06 01:19 UTC, merged

2024-11-06 01:21 UTC, LantaoJin commented
Conflicts is related to imports. CI tests succeed with the related files. Merging to main.