[WIP] PPL geoip function pt. 2
opensearch-project/opensearch-spark pull request #871
Opened 2024-11-05 17:39 UTC by kenrickyap

Description
PPL geoip function

Issues Resolved
https://github.com/opensearch-project/opensearch-spark/issues/672

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-11-05 23:33 UTC, kenrickyap commented
Hi @YANG-DB, I heard from Anas that you had a method of implementing ip2geo functionality for Spark. I wanted to check with you that our current approach aligns with your method.

Current Plan:
Leveraging [SerializableUdf](https://github.com/opensearch-project/opensearch-spark/pull/706/files#diff-4fc2e6dc7264b8eac89050f1f19c51381f61fa36b302d78bcc0bc260498845fe) create a UDF that does the follow:

1. Check if in-memory cache object for datasource exists.
2. If cache object does not exists create new in-memory cache object from csv retrieved from datasource manifest.
3. Search cached object for GeoIP data.
4. Return GeoIP data.

All of this would have to be implemented within the Spark library, as currently I am not aware of how to access any geospatial artifacts. If you know of a better way to implement ip2geo please let me know! Thanks!

2024-11-05 23:47 UTC, kenrickyap commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +            //TODO:
In-memory ip2geo functionality will be implemented here

2024-11-06 18:27 UTC, YANG-DB commented
@kenrickyap please update the DCO (contributor sign-off)

2024-11-06 18:38 UTC, YANG-DB requested changes
@kenrickyap I'm missing a more detailed design of the actual functionality that should include:
 - flow diagram of loading the geoIp data
 - storage of that data
 - utilizing of different `datasource`
 - pro/cons for the different approaches 

please add the former discussions [made](https://github.com/opensearch-project/opensearch-spark/pull/781) into this issue for better traceability

2024-11-06 18:38 UTC, YANG-DB commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
>  primaryExpression
@kenrickyap please review [this](https://github.com/opensearch-project/opensearch-spark/blob/p1-antlr-grammar/ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4) antlr p1 suggestion and see how the geoIp command is used as part of the `eval` reusing evalFunctionCall...
IMO IP function sounds not one of the primary expressions.

2024-11-06 18:38 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
> +            //TODO:
@kenrickyap can you please explain in more details the flow of the events from the beginning of the query?

2024-11-06 18:38 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystExpressionVisitor.java
> +import org.opensearch.sql.ast.expression.*;
please keep the existing explicit import list ...

2024-11-06 23:32 UTC, kenrickyap commented
**Flow diagram for ip2geo UDF**

![mermaid-diagram-2024-11-06-140042](https://github.com/user-attachments/assets/a7d48707-0348-4558-9b45-8a51a353d1d8)

**Design Details**

- Ip2GeoCache will be a Gauva Cache that has datasource string as key and CidrTree as value
- CidrTree will be Trie (will use apache.common PatriciaTrie as I see that apache.common is already included in project)
  - Am using trie instead of map as it is more well suited for longest prefix matching task, and this task is similar to ip to cidr matching
  - each CidrTreeNode will store:
    - nth bit value of cidr (n is the depth of tree)
    - geo_data if there is matching cidr row in 
    - child CidrTreeNodes
 - Will retrieve CsvParser from manifest using similar methodology as in geospatial [ip2geo](https://github.com/opensearch-project/geospatial/blob/main/src/main/java/org/opensearch/geospatial/ip2geo/dao/GeoIpDataDao.java#L188)
 
 **Pros**
 
 - ip2geo functionality is achieved.
 - implementation is simple and does not depend on any additional libraries that do not already exist in the project.
 
 **Cons**
 
 - calculations are done in-memory as a UDF, this means that multiple instances of Ip2GeoCache will be created in distributed Spark systems and they will not sync.
 - not leveraging job-scheduler to run ip2geo task and not leveraging OpenSearch to store ip2geo data as geospatial does.

2024-11-07 00:06 UTC, YANG-DB commented
> **Flow diagram for ip2geo UDF**
> 
> ![mermaid-diagram-2024-11-06-140042](https://private-user-images.githubusercontent.com/121634635/383740205-a7d48707-0348-4558-9b45-8a51a353d1d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MzcxNTksIm5iZiI6MTczMDkzNjg1OSwicGF0aCI6Ii8xMjE2MzQ2MzUvMzgzNzQwMjA1LWE3ZDQ4NzA3LTAzNDgtNDU1OC05YjQ1LThhNTFhMzUzZDFkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQyMzQ3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGE4ZTM3NzE5NDU1Y2NlOWNhNjVhNDFjOWFiZDBiZWJjZWIzOWRkYzNmMDllMmM5MmFhY2Y0ZDJmNzZkNjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xQmnmdwvtN2M2Dt0INzk-OtazcQRuErwn7ewiaKvRGg)
> 
> **Design Details**
> 
> * Ip2GeoCache will be a Gauva Cache that has datasource string as key and CidrTree as value
> * CidrTree will be Trie (will use apache.common PatriciaTrie as I see that apache.common is already included in project)
>   
>   * Am using trie instead of map as it is more well suited for longest prefix matching task, and this task is similar to ip to cidr matching
>   * each CidrTreeNode will store:
>     
>     * nth bit value of cidr (n is the depth of tree)
>     * geo_data if there is matching cidr row in datasource csv
>     * child CidrTreeNodes
> * Will retrieve CsvParser from manifest using similar methodology as in geospatial [ip2geo](https://github.com/opensearch-project/geospatial/blob/main/src/main/java/org/opensearch/geospatial/ip2geo/dao/GeoIpDataDao.java#L188)
> 
> **Pros**
> 
> * ip2geo functionality is achieved.
> * implementation is simple and does not depend on any additional libraries that do not already exist in the project.
> 
> **Cons**
> 
> * calculations are done in-memory as a UDF, this means that multiple instances of Ip2GeoCache will be created in distributed Spark systems and they will not sync.
> * not leveraging job-scheduler to run ip2geo task and not leveraging OpenSearch to store ip2geo data as geospatial does.

@kenrickyap a few questions here:
- how / is the Ip2GeoCache memory shared between sessions ? is it a signleton ? 
- plz also add the use case where the geo_data_source will be a table / index (in OpenSearch) / service (API) - lets create a general purpose facade for this to hide different datasource drivers
- I would like to see a more detailed description of the `CidrTreeNode` including an example and simple high level explanations (the geo tree diagram ?)
- explain why is it worth while to add this trie-tree instead of using a hash-map / search ?
- can u also add a pseudo-code here (in the issue) to clarity the composition ?

2024-11-08 16:23 UTC, kenrickyap commented
> @kenrickyap a few questions here:
> 
> * how / is the Ip2GeoCache memory shared between sessions ? is it a signleton ?

Yes we will create Ip2GeoCache to be a singleton. From my understanding this should allow the cache to be accessible between sessions 

> * plz also add the use case where the geo_data_source will be a table / index (in OpenSearch) / service (API) - lets create a general purpose facade for this to hide different datasource drivers

Will update the flow diagram to reflect facade for different datasource. 

However, would it be possible to provide a service (API) example usage? I am not to sure what such a datasource would be expected to return. 

Also would there be a fixed schema for an index in opensource?

> * I would like to see a more detailed description of the `CidrTreeNode` including an example and simple high level explanations (the geo tree diagram ?)

In hindsight I will just use a hashmap to store cidr geo_data where the cidr bitstring will be the key and geo_data will be a value. To preform the ip cidr matching will implement lookup function to convert ip to bitstring and reduce bit length till key is found in map.

Initially I wanted to leverage the `prefixMap` function as I thought this would find the best fitting cidr mask for a given ip in O(1), which would mean I wouldn't have to implement my own lookup function. However as I was trying implement this noticed that `prefixMap` takes a prefix and finds all keys that have the prefix, which is the opposite with what I want.

> * explain why is it worth while to add this trie-tree instead of using a hash-map / search ?

As mentioned above will use a hash-map instead of trie.

> * can u also add a pseudo-code here (in the issue) to clarity the composition ?

Will have pseudo-code and code added by EOD

2024-11-08 17:59 UTC, normanj-bitquill commented on docs/ppl-lang/planning/ppl-geoip.md
> +1. **Proposed syntax**
Perhaps also list out the values that can be used for properties.

2024-11-08 18:08 UTC, normanj-bitquill commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : GEOIP LT_PRTHS (datasource = functionArg COMMA)? ipAddress = functionArg (COMMA properties = stringLiteral)? RT_PRTHS
You could do further parsing here of `properties`. Something like:
```
... (COMMA properties =  geoipPropertiesList)? ...

geoipPropertiesList
  : geoipProperty (COMMA geoipProperty)*

geoipProperty
  : city
  | lat
  | lon
```

2024-11-08 18:08 UTC, normanj-bitquill commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
> +import org.opensearch.sql.ast.expression.*;
Avoid using `*` imports.

2024-11-08 18:10 UTC, normanj-bitquill commented on ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanEvalTranslatorTestSuite.scala
> +
Should add a TODO comment here, since it appears you intend to fill this out later.

2024-11-12 20:53 UTC, YANG-DB commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   : GEOIP LT_PRTHS (datasource = functionArg COMMA)? ipAddress = functionArg (COMMA properties = stringLiteral)? RT_PRTHS
I like this idea !!

2024-11-12 21:07 UTC, YANG-DB requested changes
@kenrickyap can u plz update the PR status and progress ?
thanks

2024-11-12 21:07 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/CidrGeoMap.java
> +        StringBuilder binary = new StringBuilder();
@kenrickyap please use the [ip library](https://github.com/opensearch-project/opensearch-spark/blob/dd9c0cfbab0ca327ba655c8aa9f9ee44404d4fce/build.sbt#L188C6-L188C55) for such text to utilis

2024-11-13 05:05 UTC, YANG-DB commented
@kenrickyap plz fix the DCO error ...

2024-11-13 05:11 UTC, YANG-DB requested changes

2024-11-13 05:11 UTC, YANG-DB commented on docs/ppl-lang/planning/ppl-geoip.md
> +1. **Proposed syntax**
we need a larger set of examples here plz

2024-11-13 05:11 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/CidrGeoMap.java
> +    private void put(String cidr, GeoIpData data) throws UnknownHostException {
@kenrickyap can we use an IP util library for these string to ip conversions ?

2024-11-13 05:11 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/DatasourceDao.java
> +        String[] parts = cidr.split("/");
same here

2024-11-13 05:11 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/TestDatasourceDao.java
> +        BitSet bitSet1 = DatasourceDao.createCidrBitSet("192.168.0.0/24"); // Example CIDR mask
more test cases needed including ipv6 and sample errors in the ip

2024-11-13 05:12 UTC, YANG-DB commented
@LantaoJin I would appreciate u'r review here as well...

2024-11-13 14:32 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/TestDatasourceDao.java
> +public class TestDatasourceDao implements DatasourceDao {
why a test class here?

2024-11-13 14:32 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/DatasourceManifest.java
> +  @JsonProperty("sha256_hash")
Seems this annotation is the only spot to use jackson?

2024-11-13 14:32 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/DatasourceDaoFactory.java
> +package org.opensearch.sql.common.geospatial;
missing header.

2024-11-13 14:32 UTC, LantaoJin commented on build.sbt
> +      "org.apache.commons" % "commons-csv" % "1.12.0",
is it a duplicated line?

2024-11-13 14:32 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/GeoIpCache.java
> +                .expireAfterWrite(3, TimeUnit.DAYS)
The TTL should be configurable

2024-11-13 14:32 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/TestDatasourceDao.java
> +package org.opensearch.sql.common.geospatial;
missing header

2024-11-13 20:37 UTC, jduo commented on build.sbt
> +      "com.fasterxml.jackson.core" % "jackson-annotations" % "2.14.2",
Hi @LantaoJin ,
What's the best way for this project to parse JSON?

2024-11-13 20:40 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/DatasourceManifest.java
> +  @JsonProperty("sha256_hash")
ObjectMapper is from Jackson

2024-11-13 20:41 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/GeoIpCache.java
> +    private static GeoIpCache cacheInstance = null;
This should be final.
The singleton pattern can be simplified in Java to have no getInstance() method:
```suggestion
    private static GeoIpCache cacheInstance = null;
    private static final GeoIpCache INSTANCE = new GeoIpCache();
```

2024-11-13 20:43 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/GeoIpCache.java
> +                .expireAfterWrite(3, TimeUnit.DAYS)
This implies the same data source can have different IPs depending on user context... is this something possible @YANG-DB ?

2024-11-13 20:44 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/ManifestDao.java
> +    manifestCsv = getDatabaseReader(manifest);
This can be moved to the constructor and made final

2024-11-13 20:45 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/TestDatasourceDao.java
> +public class TestDatasourceDao implements DatasourceDao {
This will be moved... DataSourceDaoFactory depends on this currently and will be updated to load implementations with reflection in an update on this PR.

2024-11-13 21:14 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/GeoIpCache.java
> +                .expireAfterWrite(3, TimeUnit.DAYS)
@jduo yes it is possible - lets add a use case + document this

2024-11-13 21:41 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/DatasourceManifest.java
> +  @JsonProperty("sha256_hash")
If we're OK using ObjectMapper because it's provided through AWS dependencies, I can remove use of @JsonProperty to get rid of Jackson databind.

2024-11-14 00:34 UTC, jduo commented on build.sbt
> +      "org.apache.commons" % "commons-csv" % "1.12.0",
Yes looks to be a typo.

2024-11-14 00:48 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/GeoIpCache.java
> +                .expireAfterWrite(3, TimeUnit.DAYS)
This really can't be a singleton in that case. We need to store this with the session/user context. How might we access this @YANG-DB ? Or we make it a multi-level cache or use a composite key for the cache.

2024-11-14 07:56 UTC, qianheng-aws commented
> * Ip2GeoCache will be a Gauva Cache that has datasource string as key and CidrTree as value
> *

questions about the design:

1. The UDF will only be executed on Spark Executor. So the cache won't take effect actually, it will be destroyed once the task has finished. Do we have mechanism to avoid this?
2. The CSV data is nearly 500MB for the datasource of `https://geoip.maps.opensearch.org/v1/geolite2-city/manifest.json`, I guess it will get bigger if populating a trie tree on it. It think it will be a big memory pressure for Spark Executor.
3. Have we ever considered retrieving the geo data by calling the related API of service like OpenSearch [geospatial](https://github.com/opensearch-project/geospatial)? Then we don't have to load the above CSV in executor memory. But I'm not quite sure whether it's feasible to do that on Serverless Spark.

2024-11-15 01:08 UTC, kenrickyap commented
> > * Ip2GeoCache will be a Gauva Cache that has datasource string as key and CidrTree as value
> 
> @kenrickyap questions about the design:
> 
> 1. The UDF will only be executed on Spark Executor. So the cache won't take effect actually, it will be destroyed once the task has finished. Do we have mechanism to avoid this?

The JVM will persist on the worker node, so udf tasks that are carried out in the same worker node will be able to leverage the cache. In any case from above comments we will be shifting away from using a singleton and implement some other method of persisting queried results.

> 2. The CSV data is nearly 500MB for the datasource of `https://geoip.maps.opensearch.org/v1/geolite2-city/manifest.json`, I guess it will get bigger if populating a trie tree on it. I think it will be a big memory pressure for Spark Executor.

yes this will be the case, this would be an initial method of performing geo2ip, there is plan to add less expensive methods of performing operation in future.

> 3. Have we ever considered retrieving the geo data by calling the related API of service like OpenSearch [geospatial](https://github.com/opensearch-project/geospatial)? Then we don't have to load the above CSV in executor memory. But I'm not quite sure whether it's feasible to do that on Serverless Spark.

yes the initial plan was to use the geospatial plugin, but geospatial does not publish any jars, and I could not find a way to leverage it's functionality for Spark. A client jar for the plugin is currently being created, a plan is discussed here: **https://github.com/opensearch-project/sql/issues/3038**. The plan was to have a follow up task where we leverage the use of this client, when it is implemented, however every as there was an urgent ask for this functionality, we opted to implement an in-engine method in parallel.

There has also been ask to be able to retrieve data from OpenSearch Index and general APIs, these methods will also be added in future issue

2024-11-15 01:43 UTC, LantaoJin commented
>> 1. The UDF will only be executed on Spark Executor. So the cache won't take effect actually, it will be destroyed once the task has finished. Do we have mechanism to avoid this?

> The JVM will persist on the worker node, so udf tasks that are carried out in the same worker node will be able to leverage the cache.

Not exactly. It depends on how the user deploys Spark. In most cases, when the dynamic resource allocation enabled, when an executor is idle for a while, e.g. no active task is running on this executor in 60 seconds, the executor process (JVM) will be released. The cache won't take effect any more.

>> 2. The CSV data is nearly 500MB for the datasource of https://geoip.maps.opensearch.org/v1/geolite2-city/manifest.json, I guess it will get bigger if populating a trie tree on it. I think it will be a big memory pressure for Spark Executor.

> yes this will be the case, this would be an initial method of performing geo2ip, there is plan to add less expensive methods of performing operation in future.

What's the plan? I can't agree this initial method where each executor hosts huge memory and the cache doesn't take effect. At least the memory/cache should be built in a lazy mode, for users who doesn't use this geoip function.

2024-11-15 03:51 UTC, LantaoJin commented
My thought is that from the perspective of open-source project, we only need to provide an interface for using IP services and a configuration-based data source connector, but do not actually provide specific IP lookup services. Users need to configure or deploy IP data source services that they can use. For example, users need to complete the configuration and authorization of web services, such as https://dev.maxmind.com/geoip/geolocate-an-ip/web-services/
For AOS, an internal service for ip lookup should be deployed.

2024-11-16 01:32 UTC, YANG-DB commented
> My thought is that from the perspective of open-source project, we only need to provide an interface for using IP services and a configuration-based data source connector, but do not actually provide specific IP lookup services. Users need to configure or deploy IP data source services that they can use. For example, users need to complete the configuration and authorization of web services, such as https://dev.maxmind.com/geoip/geolocate-an-ip/web-services/
> For Amazon OpenSearch Service (AOS), an internal service for ip lookup should be deployed. 
> 
> Another thought is that we create two tables (IPv4 and IPv6) in Glue as builtin tables. Each IP lookup can be converted to a Join operator with one of the IP table.

I agree with @LantaoJin about the interface approach - but we can definitely support a default in-memory implementation for this to work out of the box

2024-11-16 03:08 UTC, kenrickyap commented
## GeoIP Implementation Options and Path Forward

**Current Status**
The in-engine implementation of GeoIP functionality has core features working, with remaining work focused on tests, parameter filtering, and caching improvements.

### Implementation Options

**Option 1: In-Engine Implementation**

**Approach**: Perform IP lookups within the engine using in-memory processing

**Pros**:

- Simpler deployment (no external dependencies)
- Lower latency for lookups
- Immediate availability after setup
- Consistent performance

**Cons**:

- Higher memory usage (~1.3GB JVM OnHeap per worker)
- Memory scales with worker nodes
- Limited flexibility in updating GeoIP database

**Option 2: External Service Integration**

**Approach**: Offload IP lookups to external services or database

**Pros**:

- Lower memory footprint on worker nodes
- More flexible updating of GeoIP database
- Scalable independent of worker nodes
- Potential for more accurate/updated data

**Cons**:

- Additional setup complexity for users
- External service dependencies
- Potential latency overhead
- Network bandwidth considerations

### Technical Implementation Details

**In-Engine Implementation**

- Uses ManifestDao for IP lookups
- Singleton cache for IP lookup table
- Direct integration with current geospatial module

**External Service Implementation**

- API datasource DAO for service integration
- Query-level result caching
- Configurable datasource options:
```
  geoip:
    datasource:
      type: “service|database”
      connection:
        # Service-specific configuration
        endpoint: “”
        credentials: “”
        # Or database-specific configuration
        table: “”
        index: “”
  ```
### Path Forward

**Proposed Approach**

We’re considering two potential paths:

1. **Phased Implementation:**
  - Implement in-engine solution first
  - Add external service support later
  - Allows for gradual transition
2. **Direct External Implementation:**
  - Focus directly on external service integration
  - Skip in-engine implementation
  - Faster path to scalable solution

### Next Steps

1. Complete current PR to release-ready state
2. Create RFC for API interface design
3. Present both options to community for feedback
4. Proceed based on community consensus

### Discussion Points

- Memory vs. latency tradeoffs
- Deployment complexity considerations
- Maintenance and updating strategies
- Migration path for existing users

### Seeking Feedback On

- Which path would be recommended moving forward?
- Design review on RFC for API interface design (Will provide RFC soon!)

2024-11-17 08:24 UTC, andy-k-improving commented on build.sbt
> +      "com.fasterxml.jackson.core" % "jackson-annotations" % "2.14.2",
We can probably use the Jackson dep, but with the version that defined on line: 12, with runtime only scope.
```
lazy val jacksonVersion = "2.15.2"
```

2024-11-17 08:24 UTC, andy-k-improving commented on docs/ppl-lang/planning/ppl-geoip.md
> +    - `... | eval geoinfo = geoip("abc", ipAddress, "city,lat,lon")`
Would be great to also list out all the supported attributes (ex: City, Lat.....etc) along with the respective data type.

2024-11-17 08:24 UTC, andy-k-improving commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
> +//GEOLOCATION PROPERTIES
Will this list stay consistent across different implementation, or this is just for `ip2geo`?

2024-11-17 08:24 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/DatasourceManifest.java
> +    private static final int MANIFEST_FILE_MAX_BYTES = 1024 * 8;
What the usage of this MAX_BYTES declaration?
We don't seem to have any reference for this var in the projec.

2024-11-17 08:24 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/DatasourceManifest.java
> +  public String provider;
Should we have this as enum instead?
So later on we can do a Java `switch` to route the enrichment request during runtime.

2024-11-17 08:24 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/GeoIpData.java
> +public class GeoIpData {
Will this data model specific to any data provider? 
Or this is generic for all future integration for new data source?

2024-11-17 08:24 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/ManifestDao.java
> +    int cidr_index = headerMap.get("cidr");
Will there be any null check on these columns? 
Also how's the handling will be like? (Ex: Treat it as corrupted file, and abort....etc)

2024-11-18 19:49 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/common/geospatial/ManifestDao.java
> +      "https://geoip.maps.opensearch.org/v1/geolite2-city/manifest.json";
The DATASOURCE_ENDPOINT variable isn't going to be used now. Instead the user will supply a manifest URL as part of the function call.

However downloading from user-supplied links is a security concern. This code is a simplified version of the manifest-reading code from the geospatial plugin:
https://github.com/opensearch-project/geospatial/blob/10a076a41cc6e3fe23061a198c1f55c1e1c402f8/src/main/java/org/opensearch/geospatial/ip2geo/dao/GeoIpDataDao.java#L174

Glancing at it, it seems there's some URL whitelisting and running the request in a privileged action. Would it be a good path going forward to replicate this behavior?

2024-11-18 20:34 UTC, kenrickyap commented
@YANG-DB question regarding key needed for user session caching, would this be information obtainable from the Spark instance?
Was looking through the environment variables and saw `hadoop.http.staticuser.user`, would this or some other spark env param be suitable? Another option is to have the user input some configuration on Spark start up.

2024-11-18 20:36 UTC, YANG-DB commented
> @YANG-DB question regarding key needed for user session caching, would this be information obtainable from the Spark instance? Was looking through the environment variables and saw `hadoop.http.staticuser.user`, would this or some other spark env param be suitable? Another option is to have the user input some configuration on Spark start up.

@kenrickyap we need to validate this with different spark providers such as the local out of the box spark  / EMR managed spark and such...

2024-11-19 00:49 UTC, kenrickyap commented
Based on discussion with @YANG-DB. Will shift implementation to only support Spark tables, where task of creating lookup table will be pushed to user. This shift will mean that there is no longer any reliance on UDF and performing ip2geo lookup in memory.

Specifically:
- geoip default behaviour is to perform join on predefined spark table. (Table name will be provided as config during spark startup.)
- pre-defined table schema is expected for geoip function to work. This will be documented.
- part of PR is to provide user with instructions to create spark geoip table.

We will provide ability to use other datasources for ip lookup in future tasks.

2024-11-19 08:19 UTC, LantaoJin commented
> Based on discussion with @YANG-DB. Will shift implementation to only support Spark tables (with intention to support other datasources in future), where task of creating lookup table will be pushed to user. This shift will mean that there is no longer any reliance on UDF and performing ip2geo lookup in memory.
> 
> Specifically:
> 
> * geoip default behaviour is to perform join on predefined spark table. (Table name will be provided as config during spark startup.)
> * pre-defined table schema is expected for geoip function to work. This will be documented.
> * part of PR is to provide user with instructions to create spark geoip table.
> 
> We will provide ability to use other datasources for ip lookup in future tasks.

Sounds good. I like this solution but it's still very challenging! The primary problem to solve in this solution is how to build a `Partitioner`: `HashPartitioner` doesn't work with CIDR notation. For example 1.0.1.0/24 includes all listings from 1.0.1.1 to 1.0.1.255, or we have to expand all IPv4 and IPv6 listings to a spark table.

2024-11-19 21:38 UTC, kenrickyap commented
@LantaoJin @YANG-DB This is the current details for the new implementation. Please let us know if there is any concerns or comments :)

Feature will include two parts:

- Scala script provided in docs that user will run to download data and create spark table.
- `geoip` function that will perform join on specified table.

### Details on Scala Script

#### User flow

- user will run script on spark-shell
- script will:
  1. download manifest from https://geoip.maps.opensearch.org/v1/geolite2-city/manifest.json and retrieve csv.
  2. parse csv and create spark dataframe.
  3. create new spark table `geoip_table` from dataframe.
    - table will have the following schema:
       cidr, country_iso_code ,country_name, continent_name, region_iso_code, region_name, city_name, time_zone, location
  4. add following columns to `geoip_table`: 
    - `ip_range_start` - type: `long` - first ip address in CIDR range (will ensure range is distinct does not overlap)
    - `ip_range_end` - type: `long` - last ip address in CIDR range (will ensure range is distinct does not overlap)
    - `ip_type` - type: `string` - IPv4 or IPv6
    
### Details of `geoip` implementation

`geoip` will have 3 inputs:
  - `datasource` - currently unused (will keep for future feature of letting users query API/Opensearch index datasources). 
  - `ip_address` - ip_address to get geo_info on
  - `parameters` - which columns will be selected from `geoip_table`.

#### ip2geo lookup details

To perform ip2geo look up we will perform join on `geoip_table` with the following conditions:

- geoip_table.ip_start_end <= ip_address <= geoip_table.ip_range_end
  - geo_table name will be provided at spark start up as config (e.g. --conf spark.geoip.tablename = `geoip_table`)
- ip_address.type = ip_type (will check IP type using inet library)

### Implementation clarification questions

- Regarding AWS EMR Spark, will the shell script be able to download manifest?
  - If not we can alter the script such that user needs to provide filepath to script, and offload csv retrieval to user
- Regarding @LantaoJin's suggestions to use `Partitioner`, I am not to sure how to integrate this given the current design. Currently my guess is that each node of the partition would be a different sub range, and we would query sub range directly to reduce load? Is this the right interpretation or am I missing something?

2024-11-19 23:50 UTC, YANG-DB commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
> +//GEOLOCATION PROPERTIES
@kenrickyap lets try to align according to this schema

2024-11-20 00:09 UTC, YANG-DB commented
> @LantaoJin @YANG-DB This is the current details for the new implementation. Please let us know if there is any concerns or comments :)
> 
> Feature will include two parts:
> 
> * Scala script provided in docs that user will run to download data and create spark table.
> * `geoip` function that will perform join on specified table.
> 
> ### Details on Scala Script
> #### User flow
> * user will run script on spark-shell
> * script will:
>   
>   1. download manifest from https://geoip.maps.opensearch.org/v1/geolite2-city/manifest.json and retrieve csv.
>   2. parse csv and create spark dataframe.
>   3. create new spark table `geoip_table` from dataframe.
>   
>   
>   * table will have the following schema:
>     cidr, country_iso_code ,country_name, continent_name, region_iso_code, region_name, city_name, time_zone, location
>   
>   
>   4. add following columns to `geoip_table`:
>   
>   
>   * `ip_range_start` - type: `long` - first ip address in CIDR range (will ensure range is distinct and does not overlap)
>   * `ip_range_end` - type: `long` - last ip address in CIDR range (will ensure range is distinct and does not overlap)
>   * `ip_type` - type: `string` - IPv4 or IPv6
> 
> ### Details of `geoip` implementation
> `geoip` will have 3 inputs:
> 
> * `datasource` - currently unused (will keep for future feature of letting users query API/Opensearch index datasources).
> * `ip_address` - ip_address to get geo_info on
> * `parameters` - which columns will be selected from `geoip_table`.
> 
> #### ip2geo lookup details
> To perform ip2geo look up we will perform join on `geoip_table` with the following conditions:
> 
> * geoip_table.ip_start_end <= ip_address <= geoip_table.ip_range_end
>   
>   * geo_table name will be provided at spark start up as config (e.g. --conf spark.geoip.tablename = `geoip_table`)
> * ip_address.type = ip_type (will check IP type using inet library)
> 
> ### Implementation clarification questions
> * Regarding AWS EMR Spark, will the shell script be able to download manifest?
>   
>   * If not we can alter the script such that user needs to provide filepath to script, and offload csv retrieval to user
> * Regarding @LantaoJin's suggestions to use `Partitioner`, I am not to sure how to integrate this given the current design. Currently my guess is that each node of the partition would be a different sub range, and we would query sub range directly to reduce load on join? Is this the right interpretation or am I missing something?

Hi @kenrickyap 
Thanks for the detailed information 👍 here are my comments:
 - no need to download the [manifest-file](https://geoip.maps.opensearch.org/v1/geolite2-city/manifest.json) you should copy it locally to this repo (since its only an example and not a production use-case ).
 - A user can be expected to provide this file and use S3 file location for this purpose - we can instruct EMR users to manually upload the file into S3 and use the `create table ... using ... ` to load the data from there.
 - what is the expected size of this table ? (rows / memory) - plz test and verify
 - table structure: `ip_type` - type: `string` - IPv4 or IPv6 - why not use a bool ? (ipv4 columns)

2024-11-20 00:11 UTC, YANG-DB commented
@kenrickyap 
another request - please run `explain cost |  ip2geo ...`  to see how the query cost is estimated by the engine with resect to the amount of rows..,,

2024-11-20 00:48 UTC, kenrickyap commented
Thanks for the feedback :) have updated design to address comments. As for question responses:

> * what is the expected size of this table ? (rows / memory) - plz test and verify

Table has about 5 million rows, and is about 500 MB.

> * please run explain cost |  ip2geo ... to see how the query cost is estimated by the engine with relation to the amount of actual rows..

Will verify this when the command is implemented

2024-11-20 03:31 UTC, LantaoJin commented
> #### ip2geo lookup details
> To perform ip2geo look up we will perform join on `geoip_table` with the following conditions:
> 
> * geoip_table.ip_start_end <= ip_address <= geoip_table.ip_range_end

> * Regarding @LantaoJin's suggestions to use `Partitioner`, I am not to sure how to integrate this given the current design. Currently my guess is that each node of the partition would be a different sub range, and we would query sub range directly to reduce load on join? Is this the right interpretation or am I missing something?

The integer range from `ip_start_start` to `ip_start_end` between each CIDR notation should be ordering and no overlapping. Since Spark has a `RangePartitioning` default implementation, the Join operator with join condition `geoip_table.ip_start_start <= ip_address AND ip_address <= geoip_table.ip_range_end` would perform `RangeJoin` in optimal. But I realized there is **no** range join implementation in Apache Spark and EMR Spark currently. (Databricks Runtime has supported it https://docs.databricks.com/en/optimizations/range-join.html). So the join operator will perform `NestedLoopJoin` finally. So I think the performance won't be good but no necessary to consider how to leverage `RangePartitioning` in right now.

2024-11-28 23:08 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
> +
?

2024-11-28 23:08 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/GeoIp.java
> +package org.opensearch.sql.ast.tree;
License header

2024-11-28 23:08 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/GeoIp.java
> +@ToString
I couldn't find the use age of ToString and Getter in this codebase.

2024-12-05 22:06 UTC, normanj-bitquill commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
> +
I think that adding the blank line here is better formatting.

2024-12-05 22:35 UTC, normanj-bitquill commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   | geoipCommand
How about standardizing this a bit more. Such as:
```
evalClause
   : fieldExpression EQUAL evalClauseExpression
   ;
evalClauseExpression
   : expression
   | GEOIP LT_PRTHNS ipAddress = functionArg (COMMA properties = geoIpPropertyList)? RT_PRTHNS
   ;
```

Hopefully this would mean that you no longer need to change the `Eval` class, since it will always contain LET expressions.

2024-12-05 22:38 UTC, normanj-bitquill commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoipCatalystUtils.java
> +public interface GeoipCatalystUtils {
Can this get a name that doesn't include `Utils`, such as `GeoIpCatalystLogicalPlanGenerator`?

2024-12-05 22:39 UTC, kenrickyap commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   | geoipCommand
I couldn't find a way to represent a join using a LET as LET is treated as an Expressions and can no longer effect the Logical Plan.

2024-12-06 00:18 UTC, YANG-DB requested changes

2024-12-06 00:18 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
>  public interface SerializableUdf {
@kenrickyap can we rename the method in this class to be indicative of being related to the `geoiplocation` feature ?
maybe add an internal static class ?

2024-12-06 00:18 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoipCatalystUtils.java
> +public interface GeoipCatalystUtils {
Or maybe `GeoIpCatalystLogicalPlanTranslator`

2024-12-06 00:18 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoipCatalystUtils.java
> +    static LogicalPlan applyJoin(Expression ipAddress, CatalystPlanContext context) {
please add some javadoc explanations

2024-12-06 00:18 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoipCatalystUtils.java
> +            attributeListToUse = List.of(
can the strings here be extracted into static final const?

2024-12-06 00:18 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
> +                    propertyName = "COUNTRY_ISO_CODE";
can we make this enum ?

2024-12-06 00:54 UTC, kenrickyap commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
> -GEOIP:                              'GEOIP';
It was re-added in another location

2024-12-06 00:54 UTC, kenrickyap commented on README.md
> -sbt clean sparkPPLCosmetic/publishM2
Added back

2024-12-08 23:07 UTC, kenrickyap commented on docs/ppl-lang/planning/ppl-geoip.md
> +1. **Proposed syntax**
added additional examples in ppl_ip.md doc

2024-12-08 23:07 UTC, kenrickyap commented on docs/ppl-lang/planning/ppl-geoip.md
> +    - `... | eval geoinfo = geoip("abc", ipAddress, "city,lat,lon")`
added in ppl_ip.md doc

2024-12-08 23:18 UTC, kenrickyap commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
> +   | geoipCommand
LET is refers to an expression tree node type that EVAL uses by default to represent child nodes. This node type is not able to rewrite the AstTree into a join as it is an expression and thus cannot influence the logical plan. As GeoipCommand must be a child of Eval and modify the AstTree into a join it does not use the Let node type but is rather an UnresolvedPlan which can rewrite the AstTree.

Have added comment to explain this

2024-12-08 23:18 UTC, kenrickyap commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
>  public interface SerializableUdf {
done

2024-12-09 18:36 UTC, kenrickyap commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
> +                    propertyName = "COUNTRY_ISO_CODE";
done

2024-12-09 18:36 UTC, kenrickyap commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoipCatalystUtils.java
> +            attributeListToUse = List.of(
done

2024-12-09 18:36 UTC, kenrickyap commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoipCatalystUtils.java
> +    static LogicalPlan applyJoin(Expression ipAddress, CatalystPlanContext context) {
added docs

2024-12-09 19:06 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
> +            return context.apply(p -> p);
why no just use `context.getPlan()` ?

2024-12-09 19:10 UTC, YANG-DB commented on docs/ppl-lang/planning/ppl-geoip.md
> +2. **Proposed wiring with the geoip database**
please change the wording from `Proposed` to implementation.

2024-12-09 19:12 UTC, YANG-DB reviewed
@kenrickyap 
please add the explanation of how the geoIP is resolved using the join and detail the future plan for additional data-sources to use 
IMO it should be added in the `ppl-geoip.md` doc

2024-12-09 19:13 UTC, YANG-DB commented
@kenrickyap please also add the  `Signed-off-by: Author Name <authoremail@example.com>` in every commit message.

2024-12-11 02:27 UTC, YANG-DB approved these changes

2024-12-11 02:27 UTC, YANG-DB commented
@kenrickyap can u plz fix the DCO ?(developer certification)
thanks

2024-12-11 23:08 UTC, andy-k-improving commented
@kenrickyap If this is ready, can. you remove the Draft tag also?

2024-12-17 19:04 UTC, kenrickyap commented
@LantaoJin would you be able to provide a review?

2024-12-18 02:12 UTC, andy-k-improving requested changes

2024-12-18 02:12 UTC, andy-k-improving commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
> +CITY_NAME:                          'CITY_NAME';
`time_zone` seems missing from the list, as per `ppl-ip.md` described.

2024-12-18 02:13 UTC, andy-k-improving commented
@kenrickyap I only conducted the review for half of the changes, will continue tomorrow, also checkstyle is failing on CI, would you mind to fix?
Thanks,

2024-12-18 02:47 UTC, YANG-DB commented
@kenrickyap can u see why the build is failing ?

2024-12-18 18:34 UTC, kenrickyap commented on docs/ppl-lang/planning/ppl-geoip-command.md
> +        SELECT source.*, struct(geoip.country_name, geoip.city_name) AS a
yes, if one property is provided a string will be returned, else a struct will be returned

2024-12-18 18:47 UTC, YANG-DB requested changes

2024-12-18 18:47 UTC, YANG-DB commented on ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanGeoipFunctionTranslatorTestSuite.scala
>      val is_ipv4 = ScalaUDF(
@kenrickyap please change the usage of `ScalaUDF` to call the [`ScalaUDF.visit(...)`](https://github.com/opensearch-project/opensearch-spark/blob/957de4e27d3a243ccb9beccd2ee72ab231e9dcf4/ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java#L151)

2024-12-18 18:47 UTC, YANG-DB commented on ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanGeoipFunctionTranslatorTestSuite.scala
@kenrickyap please also add tests that have `fields ...` in the query and test behaviour of the following cases:
 - fields match exactly `geoip` requested fields
 - fields missing some `geoip` requested fields
 - fields contains fields from table that collide with `geoip` requested fields
 -

2024-12-18 18:53 UTC, kenrickyap commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLGeoipITSuite.scala
> +  test("test geoip with no parameters") {
would this be redundant as logical plan is already tested in integration tests within ppl project?

2024-12-18 18:55 UTC, kenrickyap commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
> +CITY_NAME:                          'CITY_NAME';
time_zone is already set in other part of lexer, would it be preferred to create a new Alias for geoip specifically?

2024-12-18 18:56 UTC, kenrickyap commented on docs/ppl-lang/planning/ppl-geoip-command.md
> +- `... | eval geoinfo = geoip([datasource,] ipAddress *[,properties])`
this is needed for future implementations of geoip, as this is part of the planning docs chose not to exclude. Would it be preferred to remove this reference?

2024-12-18 19:39 UTC, andy-k-improving commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLGeoipITSuite.scala
> +  test("test geoip with no parameters") {
Nope, it's similar but not identical, unit-test is purposed to assert the logical plan itself, but not the correctness of the result, as there is no runtime-spark being involved.

On the other side, integ-test is purposed, to first make sure the expected logical plan is being produced AND the ideal results being generated by the given logical-plan.

By considering this, any future code changes result in change of the logical plan should fail BOTH Unit and Integration test, but not either.

2024-12-18 20:03 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
> +    String SOURCE_TABLE_ALIAS = "t1";
The name seems to be too generic, will this cause error when user already has a table call `t1` in the PPL command?
You can probably add a prefix `__GEO_IP__` or something similar to avoid the conflict.

2024-12-18 20:04 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
> +    List<String> GEOIP_TABLE_COLUMNS = List.of(
Just a suggestion, can we construct this list from the enum on Line:229 instead.
Or else in the future when we update one, we may missed the other. 
```
enum GeoIpProperty {
        COUNTRY_ISO_CODE,
        COUNTRY_NAME,
        CONTINENT_NAME,
        REGION_ISO_CODE,
        REGION_NAME,
        CITY_NAME,
        TIME_ZONE,
        LOCATION
    }
```

2024-12-18 20:23 UTC, andy-k-improving requested changes

2024-12-18 20:23 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
> +                                    UnresolvedAttribute$.MODULE$.apply(seq(GEOIP_TABLE_ALIAS,"ip_range_start"))
`ip_range_start` should be a constant, similar to `String DEFAULT_GEOIP_TABLE_NAME = "geoip"`

2024-12-18 20:23 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
> +                                    UnresolvedAttribute$.MODULE$.apply(seq(GEOIP_TABLE_ALIAS,"ip_range_end"))
same

2024-12-18 20:23 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
> +                            UnresolvedAttribute$.MODULE$.apply(seq(GEOIP_TABLE_ALIAS,"ipv4"))
same.

2024-12-18 20:23 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
> +                UnresolvedAttribute$.MODULE$.apply(seq(GEOIP_TABLE_ALIAS,"cidr")),
Same, to abstract the constant, and re-use for `ip_range_x`

2024-12-18 20:23 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
> +                Option.apply("ip_to_int"),
Same for the function name

2024-12-18 20:24 UTC, andy-k-improving commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
> +CITY_NAME:                          'CITY_NAME';
If that is the case, it's ok.

2024-12-19 00:34 UTC, andy-k-improving commented on docs/ppl-lang/planning/ppl-geoip-command.md
> +- `... | eval geoinfo = geoip([datasource,] ipAddress *[,properties])`
I reckon this is debatable, @YANG-DB would appreciate your thought on this.
Do we document what has been done (The fact), or what we think it should be (The ideal slide).
Personally I prefer to only document what got implemented thou (The fact), if indeed there will be another feature owner to implement source support in the future, I rather to have him || her to update this page or mark it as obsoleted, when the time comes.

2024-12-19 00:35 UTC, andy-k-improving commented on docs/ppl-lang/planning/ppl-geoip-command.md
> +- use the default geoip datasource
If we decide to keep the multiple DS support on the doc, please ignore this.

2024-12-19 09:58 UTC, kenrickyap commented on docs/ppl-lang/planning/ppl-geoip-command.md
> +        SELECT source.*, struct(geoip.country_name, geoip.city_name) AS a
added additional plan

2024-12-19 09:58 UTC, kenrickyap commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLGeoipITSuite.scala
> +  test("test geoip with no parameters") {
ahh I see thanks for the explanation :) have added logical plan check in integ-tests

2024-12-19 09:59 UTC, kenrickyap commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLGeoipITSuite.scala
> +    assert(results.sorted.sameElements(expectedResults.sorted))
added integ-test to check that ParseException is thrown if invalid property is provided

2024-12-19 10:01 UTC, kenrickyap commented on ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
> +//GEOLOCATION PROPERTIES
current list is documented in docs and design files

2024-12-19 10:04 UTC, kenrickyap commented on ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanGeoipFunctionTranslatorTestSuite.scala
added above test cases to PPLLogicalPlanGeoipFunctionTranslatorTestSuite except for "fields contains fields from table that collide with geoip requested fields" as users table has not predefined schema. instead have created integ-test in FlintSparkPPLGeoipITSuite to test this case.

2024-12-19 10:10 UTC, kenrickyap commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
> +    String SOURCE_TABLE_ALIAS = "t1";
it won't as these aliases are added on top of pre-existing table names (e.g. t1.t1 or t1.t2 if table name is t1 or t2), and aliases are dropped after join happens so any future logical plan that uses this plan will not be confused. There is a test case of this case "test geoip function - ipAddress col exist in geoip table"

2024-12-19 10:24 UTC, kenrickyap commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
> +                UnresolvedAttribute$.MODULE$.apply(seq(GEOIP_TABLE_ALIAS,"cidr")),
addressed

2024-12-19 10:24 UTC, kenrickyap commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
> +                            UnresolvedAttribute$.MODULE$.apply(seq(GEOIP_TABLE_ALIAS,"ipv4"))
addressed

2024-12-19 10:24 UTC, kenrickyap commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
> +                                    UnresolvedAttribute$.MODULE$.apply(seq(GEOIP_TABLE_ALIAS,"ip_range_end"))
addressed

2024-12-19 10:24 UTC, kenrickyap commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
> +                                    UnresolvedAttribute$.MODULE$.apply(seq(GEOIP_TABLE_ALIAS,"ip_range_start"))
addressed

2024-12-19 10:24 UTC, kenrickyap commented on ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanGeoipFunctionTranslatorTestSuite.scala
>      val is_ipv4 = ScalaUDF(
addressed

2024-12-19 10:27 UTC, kenrickyap commented on docs/ppl-lang/planning/ppl-geoip-command.md
> +- `... | eval geoinfo = geoip([datasource,] ipAddress *[,properties])`
my opinion is that we can remove datasource for now and if we need to alter the design later we can alter the current doc. To remain consistent it might be best to have datasource params supplied by config, however the main limitation of this implementation is that users can only leverage one datasource which is a use case that should be supported.

2024-12-19 10:27 UTC, kenrickyap commented on docs/ppl-lang/planning/ppl-geoip-command.md
> +- use the default geoip datasource
removed datasource for now

2024-12-19 10:27 UTC, kenrickyap commented on docs/ppl-lang/planning/ppl-geoip-command.md
> +- `... | eval geoinfo = geoip("abc", ipAddress, city, location")`
removed datasource for now

2024-12-19 10:29 UTC, kenrickyap commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
> +                Option.apply("ip_to_int"),
I will address this commit in follow-up PR as these function names are linked to definition in SerializedUdf class. Plan is to convert SerializedUdf.visit to use enum instead of strings for function names. However as this would impact code not relevant to geoip will do this in seperate PR.

2024-12-19 17:32 UTC, YANG-DB commented on docs/ppl-lang/planning/ppl-geoip-command.md
> +### New syntax definition in ANTLR
@kenrickyap we can remove this part since its more implementation details

2024-12-19 17:35 UTC, YANG-DB commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLGeoipITSuite.scala
> +  test("test geoip with no parameters") {
@andy-k-improving great explanation !!

2024-12-19 17:48 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
> +        for (Node expr : expressions) {
@kenrickyap how about the next code:
```
for (Node expr : expressions) {
    switch (expr) {
        case Let let -> {
            Alias alias = new Alias(let.getVar().getField().toString(), let.getExpression());
            aliases.add(alias);
        }
        case UnresolvedPlan unresolvedPlan -> unresolvedPlan.accept(this, context);
        default -> throw new SyntaxCheckException("Unexpected node type when visiting EVAL");
    }
}
```

2024-12-19 17:50 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
> +        if (!aliases.isEmpty()) {
can this alias related code be moved up to the part which created the alias ?

2024-12-19 17:54 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
> +                    GeoIpCatalystLogicalPlanTranslator.GeoIpProperty.valueOf(propertyName);
can you extract this validation code into a single line ? 
create a static function and call its

2024-12-19 18:02 UTC, YANG-DB reviewed
@kenrickyap I've added a few comments
plz review - thanks

2024-12-19 18:03 UTC, kenrickyap commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
> +        if (!aliases.isEmpty()) {
this must happen after the for loop as it is the for loop that populates aliases by processing the child nodes of EVAL

2024-12-19 18:08 UTC, kenrickyap commented on docs/ppl-lang/planning/ppl-geoip-command.md
> +### New syntax definition in ANTLR
removed

2024-12-19 18:08 UTC, kenrickyap commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
> +                    GeoIpCatalystLogicalPlanTranslator.GeoIpProperty.valueOf(propertyName);
addressed

2024-12-19 18:09 UTC, kenrickyap commented
> @kenrickyap I've added a few comments plz review - thanks

@YANG-DB have addressed new PR comments, not sure if I fully understand some of the comments, have added my understanding of unaddressed comments

2024-12-19 19:26 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
> +        for (Node expr : expressions) {
oh ok sorry

2024-12-19 19:28 UTC, YANG-DB approved these changes
OK LGTM !

2024-12-19 20:09 UTC, andy-k-improving commented
Thx for the taking the time to address comments. :)

2024-12-19 23:22 UTC, YANG-DB approved these changes

2024-12-19 23:23 UTC, merged