New trend line ppl command (WMA)
opensearch-project/opensearch-spark pull request #872
Opened 2024-11-05 17:53 UTC by andy-k-improving

### Description
Introduce a new variant (WMA) for existing trendline ppl command, by compositing a logical plan similar to the following with function `nth_value( )` to calculate the WMA value by perform event look behind. 

```
-- +- 'Project ['name, 'salary, 
-- (((('nth_value('salary, 3) windowspecdefinition('age ASC NULLS FIRST, specifiedwindowframe(RowFrame, -2, currentrow$())) * 3) + 
-- ('nth_value('salary, 2) windowspecdefinition('age ASC NULLS FIRST, specifiedwindowframe(RowFrame, -2, currentrow$())) * 2)) + 
-- ('nth_value('salary, 1) windowspecdefinition('age ASC NULLS FIRST, specifiedwindowframe(RowFrame, -2, currentrow$())) * 1)) / 6) AS WMA#708]
   -- +- 'UnresolvedRelation [employees], [], false
```

### Related Issues
Prior implement for SMA formula: https://github.com/opensearch-project/opensearch-spark/pull/833

### Check List
- [ ] Updated documentation (docs/ppl-lang/README.md)
- [ ] Implemented unit tests
- [ ] Implemented tests for combination with other commands
- [ ] New added source code should include a copyright header
- [ ] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-11-06 18:41 UTC, YANG-DB requested changes
@andy-k-improving 
please add the relevant [documentation](https://github.com/opensearch-project/opensearch-spark/blob/main/docs/ppl-lang/ppl-trendline-command.md) references including [examples](https://github.com/opensearch-project/opensearch-spark/blob/main/docs/ppl-lang/PPL-Example-Commands.md)

2024-11-06 23:14 UTC, jduo commented on integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLTrendlineITSuite.scala
> +  test("test rendline wma command on evaluated column") {
```suggestion
  test("test trendline wma command on evaluated column") {
```

2024-11-06 23:19 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineCatalystUtils.java
> +        Expression WMAExpression = getNthValueAggregations(visitor, node, context, windowDefinition,
wmaExpression

2024-11-06 23:19 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineCatalystUtils.java
> +
Any chance you can provide an example of the SQL that gets produced here? Easier to read vs. examining the code.

2024-11-06 23:20 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineCatalystUtils.java
> +        return context.popNamedParseExpressions().get();
It would be good to indicate in the method name that this pops an expression.

2024-11-06 23:24 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineCatalystUtils.java
> +                    throw new IllegalArgumentException(node.getComputationType()+" requires a sort field for computation");
This seems like it's a SemanticCheckException. It's an error that happens to be due to the combination of inputs rather than a programmer error.

2024-11-06 23:25 UTC, jduo commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineCatalystUtils.java
> +     * @param i Target value for the expression.
Should indicate that this is a 1-based index.

2024-11-06 23:45 UTC, andy-k-improving commented
> @andy-k-improving please add DCO (sign-off)

Done.

2024-11-07 01:12 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineCatalystUtils.java
> +                    throw new IllegalArgumentException(node.getComputationType()+" requires a sort field for computation");
Do you mean the checking should be handled on ANTLR side instead?

I tried to set up such grammar rule on the ANLTR file, however, it doesn't support direct conditional checks on prior tokens (In this case, to enforce `SORT` only when `trendlineType == WMA`. 
Hence I end up handling the situation on the util classes instead.

2024-11-07 01:31 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineCatalystUtils.java
> +     * @param i Target value for the expression.
Would you mind to clarify on this? 
As this is a generic helper method to convert an Integer into its Expression form, there shouldn't be any array / index involved.

2024-11-07 01:31 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineCatalystUtils.java
> +        return context.popNamedParseExpressions().get();
how about `parseIntToExpression`?

2024-11-07 03:25 UTC, andy-k-improving commented
> @andy-k-improving
> 
> ## please add the relevant [documentation](https://github.com/opensearch-project/opensearch-spark/blob/main/docs/ppl-lang/ppl-trendline-command.md) references including [examples](https://github.com/opensearch-project/opensearch-spark/blob/main/docs/ppl-lang/PPL-Example-Commands.md)

Done.

2024-11-07 21:35 UTC, andy-k-improving commented
@YANG-DB I have updated the example and documentation, would you mind to have another look?

Thanks,

2024-11-12 18:16 UTC, andy-k-improving commented
Hi @dai-chen , @LantaoJin  and @salyh , would you guys mind to have look on this, any feedback would be appreciated :)

2024-11-12 22:48 UTC, YANG-DB approved these changes
@andy-k-improving this looks good - only a few questions commented

2024-11-12 22:48 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineCatalystUtils.java
> +                Math.negateExact(dataPoints - 1));
@andy-k-improving how/where do we make sure that dataPoints > 0 ?

2024-11-13 00:40 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineCatalystUtils.java
> +                Math.negateExact(dataPoints - 1));
I think that make sense to perform the check on `ANLTR` level, updated the grammar rule for this purpose to read `INTEGER_LITERAL` instead of `integerLiteral`.

Any attempt with negative number will result in syntax error upon parsing. 
```
spark-sql (default)> source=employees | trendline sort age wma(-2, salary);
line 1:42 extraneous input '-' expecting INTEGER_LITERAL

[PARSE_SYNTAX_ERROR] Syntax error at or near 'source'.(line 1, pos 0)

== SQL ==
source=employees | trendline sort age wma(-2, salary)
^^^

```

2024-11-13 05:03 UTC, YANG-DB commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineCatalystUtils.java
> +                Math.negateExact(dataPoints - 1));
@andy-k-improving thanks - plz add a test that should fail with this error 
thanks

2024-11-13 13:30 UTC, LantaoJin commented on ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
> +  NTH_VALUE(FunctionName.of("nth_value")),
This class is for PPL builtin function, not Spark. If we want to add a new PPL builtin function, `NTH_VALUE` should be added in Lexer and Parser, and user doc too. Or remove this line to avoid confusion.

2024-11-14 00:22 UTC, andy-k-improving commented on ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineCatalystUtils.java
> +                Math.negateExact(dataPoints - 1));
@YANG-DB Added test-cases on both Unit and Integration test to reflect this.

2024-11-14 02:21 UTC, LantaoJin approved these changes

2024-11-14 03:29 UTC, LantaoJin commented
The CI failure caused by https://github.com/opensearch-project/opensearch-spark/pull/903 is not related but blocks your whole testing process. @andy-k-improving could you merge the latest code from main?

2024-11-14 06:38 UTC, merged

2024-11-14 06:38 UTC, LantaoJin commented
Thanks for your contribution. Merging to main.