[DOC] Ensure PPL docs have consistent look
opensearch-project/opensearch-spark pull request #926
Opened 2024-11-18 04:57 UTC by LantaoJin

### Description
_Describe what this change achieves._

### Related Issues
Resolves https://github.com/opensearch-project/opensearch-spark/issues/925

### Check List
- [ ] Updated documentation (docs/ppl-lang/README.md)
- [ ] Implemented unit tests
- [ ] Implemented tests for combination with other commands
- [ ] New added source code should include a copyright header
- [ ] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-11-18 06:33 UTC, brijos commented on docs/ppl-lang/ppl-dedup-command.md
> +## PPL dedup command
We are inconsistently using back ticks for commands. Let's use a back tick `dedup`

2024-11-18 06:34 UTC, brijos commented on docs/ppl-lang/ppl-grok-command.md
> +## PPL Grok Command
should be lower case and include back ticks `grok`

2024-11-18 06:35 UTC, brijos commented on docs/ppl-lang/ppl-lookup-command.md
>  ## PPL Lookup Command
`lookup` as lowercase

2024-11-18 06:36 UTC, brijos commented on docs/ppl-lang/ppl-top-command.md
>  ## PPL top Command
missing back ticks `top`

2024-11-18 06:36 UTC, brijos commented on docs/ppl-lang/ppl-trendline-command.md
>  ## PPL trendline Command
missing back ticks `trendline`

2024-11-18 06:37 UTC, brijos requested changes
Left comments around using capitalization and back ticks.

2024-11-18 12:11 UTC, LantaoJin commented
> Left comments around using capitalization and back ticks.

Done. Thanks @brijos

2024-11-18 20:25 UTC, YANG-DB approved these changes

2024-11-19 01:13 UTC, YANG-DB approved these changes

2024-11-19 02:29 UTC, merged