Add some instructions to use Spark EMR docker image
opensearch-project/opensearch-spark pull request #965
Opened 2024-12-03 21:43 UTC by normanj-bitquill

### Description
Add some instruction on how to use the Spark EMR docker image to test the OpenSearch Spark PPL extension. Also included some sample files to help a user get started.

### Related Issues
* https://github.com/opensearch-project/opensearch-spark/issues/647
* https://github.com/opensearch-project/opensearch-spark/issues/601

### Check List
- [ ] Updated documentation (docs/ppl-lang/README.md)
- [ ] Implemented unit tests
- [ ] Implemented tests for combination with other commands
- [ ] New added source code should include a copyright header
- [ ] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-12-03 22:12 UTC, YANG-DB requested changes
@normanj-bitquill this is very nice 
- I'd also like to see this running using the spark docker image
-

2024-12-03 22:12 UTC, YANG-DB commented on docs/spark-emr-docker.md
> +## Run the Spark EMR Image
please use docker-compose to simplify this part

2024-12-03 22:16 UTC, YANG-DB commented on docker/spark-emr-sample/example-app/build.sbt
> +name := "MyApp"
lets create a simple yet more complex use case application that will run multiple ppl queries and result with a  report - similar to the next [html](https://github.com/opensearch-project/opensearch-spark/blob/63222a72db21b1634878e0b729d9de4d0cac3239/build.sbt#L89) report

2024-12-03 22:18 UTC, YANG-DB commented on docker/spark-emr-sample/example-app/src/main/scala/MyApp.scala
> +        spark.sql("CREATE table foo (id int, name varchar(100))").show()
we need a more generic mechanism of creating & loading table data and running a list of dedicated PPL queries based on the table's fields
- we can use a simpler version of our IT tests for the first iteration

2024-12-05 17:46 UTC, normanj-bitquill commented on docker/spark-emr-sample/example-app/src/main/scala/MyApp.scala
> +        spark.sql("CREATE table foo (id int, name varchar(100))").show()
You are correct, but I consider that out of scope for this PR. This is work that is planned for follow up PRs. This PR is intended to provide instructions and minimal "code" for a developer to be able to run queries against docker images of Spark.

This PR is not intended to run the integration tests.

The follow up PRs would be:
1. Create docker files that are intended to be used by the integration tests. This would include containers for S3 and the dashboard server. Only focus on testing against Apache Spark release (not EMR).
2. Update integration tests to run against the docker containers. This includes loading data, running queries and verifying the output. Also includes running the integration tests from the SBT build.
3. Create docker files for running the integration tests against Spark EMR. This includes changes so that the user can choose whether integration tests run against Apache Spark or Spark EMR.

2024-12-05 17:49 UTC, normanj-bitquill commented on docker/spark-emr-sample/example-app/build.sbt
> +name := "MyApp"
This PR is intended to provide instructions so that a developer could run queries against docker images of Spark.

I think that your comment here is asking to generate an HTML report of the integration test results. See my comment below, I consider integration tests out of scope for this PR.

I can add more to the app if it will help a developer better understand how to run their queries. Perhaps loading a simple table.

2024-12-05 18:32 UTC, YANG-DB commented on docker/spark-emr-sample/example-app/src/main/scala/MyApp.scala
> +        spark.sql("CREATE table foo (id int, name varchar(100))").show()
ok sound good !
thanks !

2024-12-05 18:36 UTC, YANG-DB commented on docker/apache-spark-sample/docker-compose.yml
> +        source: ../../ppl-spark-integration/target/scala-2.12/ppl-spark-integration-assembly-0.7.0-SNAPSHOT.jar
@normanj-bitquill can u plz use docker `.env` file for parametrizing the `ppl-spark-assembly-*.jar` and maybe the PORTs ?

2024-12-05 18:42 UTC, YANG-DB commented on docs/spark-docker.md
> +docker network create spark-network
why cant this be done in the docker-compose file ?

2024-12-05 18:43 UTC, YANG-DB commented on docs/spark-docker.md
> +Within the Spark Shell, you can submit queries, including PPL queries.
please give an example here and link to our [example doc](https://github.com/opensearch-project/opensearch-spark/blob/main/docs/ppl-lang/local-spark-ppl-test-instruction.md)

2024-12-05 18:45 UTC, YANG-DB commented on docs/spark-docker.md
> +## Docker Compose Sample
IMO this should be the first step and the actual specific detailed instruction for running each spark element should be last

2024-12-05 19:52 UTC, YANG-DB commented
@normanj-bitquill 
can u plz add sign-off for the next commit ?
`  8a3155bbe89a7775a2551fcaa1914a8e65eb0b8e    The sign-off is missing.`
thanks

2024-12-05 21:56 UTC, normanj-bitquill commented on docs/spark-emr-docker.md
> +## Run the Spark EMR Image
Added a `docker-compose.yml` for EMR.

2024-12-05 21:57 UTC, normanj-bitquill commented on docker/apache-spark-sample/docker-compose.yml
> +        source: ../../ppl-spark-integration/target/scala-2.12/ppl-spark-integration-assembly-0.7.0-SNAPSHOT.jar
Added a sample `.env` file for the host ports and the PPL Jar location. `*` doesn't work in the PPL location in a `.env` file.

2024-12-05 21:57 UTC, normanj-bitquill commented on docs/spark-docker.md
> +## Setup
See the comment above. This was added.

2024-12-05 21:58 UTC, normanj-bitquill commented on docs/spark-docker.md
> +Create a local build or copy of the OpenSearch Spark PPL extension. Make a note of the
Added the `sbt` command.

2024-12-05 21:59 UTC, normanj-bitquill commented on docs/spark-docker.md
> +docker network create spark-network
It can, and should be more clear in the documentation now. There are two sections, one for using docker compose and one for manual setup. `docker network create ...` is only needed for the manual setup.

2024-12-05 22:00 UTC, normanj-bitquill commented on docs/spark-docker.md
> +Within the Spark Shell, you can submit queries, including PPL queries.
Added an example and a link to the example doc.

2024-12-05 22:00 UTC, normanj-bitquill commented on docs/spark-docker.md
> +## Docker Compose Sample
Moved up much higher in the file. There are two main sections, using docker compose and manual setup. Using docker compose comes first.

2024-12-05 22:02 UTC, normanj-bitquill commented
> @normanj-bitquill Mostly small comments can u also add a docker-compose for emr ? if its too much effort lets add this in the next phase ... thanks

This has been added. I feel it fits in this PR, since it allows developers to make use of what I have found so far.

2024-12-05 22:02 UTC, normanj-bitquill commented
> @normanj-bitquill can u plz add sign-off for the next commit ? ` 8a3155bbe89a7775a2551fcaa1914a8e65eb0b8e The sign-off is missing.` thanks

Fixed the offending commit. All commits are not signed-off.

2024-12-05 22:03 UTC, normanj-bitquill commented
@YANG-DB I have updated this. Take another look when you have time.

2024-12-06 00:54 UTC, YANG-DB approved these changes

2024-12-06 00:55 UTC, YANG-DB commented
@LantaoJin @penghuo @dai-chen 
could u plz also review and give some feedback here ?
thanks

2024-12-06 23:29 UTC, merged