Implement FlintJob to handle all query types in warmpool mode
opensearch-project/opensearch-spark pull request #979
Opened 2024-12-09 18:16 UTC by saranrajnk

### Description

This PR introduces support for FlintJob to handle all types of queries — interactive, streaming, and batch — with all data sources in warmpool mode. Additionally, FlintJob will also support non-warmpool mode for streaming and batch queries, configurable via a Spark configuration setting.

**Changes:**

- FlintJob does not use sessionId for query execution.
- The client assigns the query at runtime for all query types in warmpool mode and executes them.
- FlintJob now supports interactive queries by reusing several functions from FlintREPL, with access modifiers updated to public.
- Added configuration for non-warmpool mode to support streaming and batch queries.
- Emits metrics success, failure and latency metrics

### Related Issues

### Check List
- [ ] Updated documentation (docs/ppl-lang/README.md)
- [ ] Implemented unit tests
- [ ] Implemented tests for combination with other commands
- [ ] New added source code should include a copyright header
- [ ] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-12-12 17:35 UTC, andy-k-improving commented on spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
> +      val jobType = sparkSession.conf.get("spark.flint.job.type", FlintJobType.BATCH)
Any particular reason to have the conf key hard-coded here?
We can probably do `FlintSparkConf.JOB_TYPE.key`, which similar to `FlintSparkConf.WARMPOOL_ENABLED.key,` on above.

2024-12-12 17:35 UTC, andy-k-improving commented on spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
> +      val dataSource = conf.get("spark.flint.datasource.name", "")
Same for `DATA_SOURCE_NAME`

2024-12-13 03:18 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
> +      val jobType = sparkSession.conf.get("spark.flint.job.type", FlintJobType.BATCH)
The [existing code](https://github.com/opensearch-project/opensearch-spark/blob/main/spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala#L33) was doing the same; I just wrapped it in an `if` block. I can modify this if needed.

2024-12-13 03:18 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
> +      val dataSource = conf.get("spark.flint.datasource.name", "")
The [existing code](https://github.com/opensearch-project/opensearch-spark/blob/main/spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala#L37) was doing the same; I just wrapped it in an `if` block. I can modify this if needed.

2024-12-16 23:42 UTC, ykmr1224 requested changes
Can you clarify and document how WarmPool is abstracted and can be enabled/disabled?

2024-12-16 23:42 UTC, ykmr1224 commented on spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
> +    if (!warmpoolEnabled) {
This introduced huge if/else block, which reduce the readability/maintainability a lot. Can you split the class for warmpool and original interactive job?

2024-12-16 23:42 UTC, ykmr1224 commented on spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
> +  def queryLoop(commandContext: CommandContext, segmentName: String): Unit = {
This looks similar to FlintREPL.queryLoop method, but modified. It would become very difficult to maintain since we need to very carefully maintain both to be consistent.
Can you add abstraction and avoid duplicates?
Can you add abstraction and avoid duplicates?

2024-12-17 00:20 UTC, noCharger commented on spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
> +  }
This `segmentName` is specific to warmpool logic; let us create abstractions on warmpool and record metrics via AOP.

2024-12-17 00:20 UTC, noCharger commented on spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
> +  def handleCommandTimeout(
Both FlintJob and FlintREPL extends FlintJobExecutor, consider refactor common methods to FlintJobExecutor

2024-12-17 00:20 UTC, noCharger commented on spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
> +    statementContext: Map[String, Any] = Map.empty[String, Any])
what's the purpose of adding statementContext which belongs to `FlintStatement` model?

2024-12-17 00:20 UTC, noCharger commented on spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
> +    if (!warmpoolEnabled) {
+1 on this, let's abstract the common interface and move from there.

2024-12-18 17:31 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
> +    if (!warmpoolEnabled) {
Ack

2024-12-18 17:33 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
> +  def queryLoop(commandContext: CommandContext, segmentName: String): Unit = {
This redundancy is expected. After this PR is merged, FlintREPL will be deprecated. FlintJob will be the single point of entry for all types of queries.

2024-12-18 17:33 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
> +  def handleCommandTimeout(
Ack

2024-12-18 17:47 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
> +    statementContext: Map[String, Any] = Map.empty[String, Any])
The `getNextStatement` call in FlintJob retrieves all the query information, including the `statementContext`. However, when the query is a streaming or batch query, we need to invoke the `JobOperator`. Currently, the `JobOperator` class only accepts the query, queryId, and other related information, but it does not include the `statementContext`. As a result, when the `JobOperator` calls `executeStatement`, we may encounter issues. To resolve this, the `statementContext` should be passed to the `JobOperator`.

Additionally, before calling [`executeStatement`](https://github.com/opensearch-project/opensearch-spark/blob/main/spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala#L89), the `FlintStatement` is constructed. Currently, the `FlintStatement` does not include the `statementContext`. However, with the introduction of the warmpool, it becomes necessary to include the `statementContext` in the `FlintStatement`, as there is client-side logic that depends on it.

2025-01-07 17:03 UTC, ykmr1224 commented on spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
> +  private def finalizeCommand(
Is it duplicate with FlintREPL? Can you check other duplicate and avoid it whenever possible?

2025-01-08 22:29 UTC, ykmr1224 commented on spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
> +case class WarmpoolJob(
It is not a good practice to separate PR for implementation and unit test. It would also become harder to review the unit test separately.

2025-01-08 22:29 UTC, ykmr1224 commented on spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
> +  private def finalizeCommand(
Looks like the only difference is emit metrics and logging. If those are beneficial for Warmpool, should we generalize it and use for FlintREPL as well?

2025-01-10 17:59 UTC, noCharger requested changes
Can we remove the concept of interactive / batch / streaming job for warm pool?

2025-01-10 17:59 UTC, noCharger commented on spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
> +    val sessionManager = instantiateSessionManager(sparkSession, resultIndexOption)
why do we need session manager for warmpool?

2025-01-10 17:59 UTC, noCharger commented on spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
> +  def queryLoop(commandContext: CommandContext): Unit = {
why do we need the concept of query loop for warm pool?

2025-01-13 08:49 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
> +  def queryLoop(commandContext: CommandContext): Unit = {
Warmpool requires multiple iterations as well before running the actual query.

2025-01-13 08:50 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
> +    val sessionManager = instantiateSessionManager(sparkSession, resultIndexOption)
There are bunch of places where sessionManager needs to passed. The resultIndex for interactive query with custom datasource was being read from this sessionManagerImpl. So this has minimal dependency still.

2025-01-13 08:51 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
> +    val sessionManager = instantiateSessionManager(sparkSession, resultIndexOption)
> Can we remove the concept of interactive / batch / streaming job for warm pool?

Why ? This classification is required for the WP logic. Also, It would be difficult to remove this at this point. Maybe we can pick it up later if required.

2025-01-26 16:50 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
> +  private def finalizeCommand(
As per the recent refactoring, the function was removed from `Warmpool.scala`

2025-01-26 16:53 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
> +    val sessionManager = instantiateSessionManager(sparkSession, resultIndexOption)
In the latest revision, I updated `JobOperator.scala` to handle all types of queries. The branching has been removed from this file, but there are still some jobType checks used in `JobOperator.scala`

2025-01-26 17:09 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
> +    val sessionManager = instantiateSessionManager(sparkSession, Some(resultIndex))
Since `JobOperator` needs to support interactive queries, QueryResultWriter will be used. `QueryResultWriterImpl`, which handles the writing of query results, depends on `sessionManager`.

That's why `sessionManager` is being introduced here to satisfy this dependency (for interactive queries)

Reference: https://github.com/opensearch-project/opensearch-spark/blob/main/spark-sql-application/src/main/scala/org/apache/spark/sql/QueryResultWriterImpl.scala#L20

2025-01-30 16:36 UTC, ykmr1224 approved these changes

2025-01-30 20:04 UTC, YANG-DB approved these changes

2025-01-30 20:06 UTC, YANG-DB commented on spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
> +    val sessionManager = instantiateSessionManager(sparkSession, Some(resultIndex))
@saranrajnk this information is critical 
IMO it would be best adding a markdown doc that explains the job operation sequence and inner details for clarity and future enhancements
thanks

2025-02-05 09:40 UTC, noCharger reviewed
Let's document this WP job somewhere, also the new configurations introduced by WP

2025-02-05 09:40 UTC, noCharger commented on spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
>      // TODO: Update FlintJob to Support All Query Types. Track on https://github.com/opensearch-project/opensearch-spark/issues/633
nit: remove the line, since this PR is to resolve this issue

2025-02-05 09:40 UTC, noCharger commented on spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
> +      if (!throwableHandler.hasException && isStreamingOrBatch) {
batch job doesn't have monitor, this logic change will cause job failure

2025-02-05 09:40 UTC, noCharger commented on spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
> +  val segmentName = getSegmentName(sparkSession)
let's document these conf

2025-02-05 09:40 UTC, noCharger commented on spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
> +            val jobType = spark.conf.get(FlintSparkConf.JOB_TYPE.key, FlintJobType.BATCH)
can we introduce wp as a new job type?

2025-02-05 09:40 UTC, noCharger commented on spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
> +}
duplicate with https://github.com/opensearch-project/opensearch-spark/pull/979/files#diff-6376f87364ce454536e56511495af6644552474c8eaf7be24c3d31d1dbad22ddR72-R86, can we refactor?

2025-02-05 09:40 UTC, noCharger commented on spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
> +    statementContext: Map[String, Any] = Map.empty[String, Any])
> Additionally, before calling [executeStatement](https://github.com/opensearch-project/opensearch-spark/blob/main/spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala#L89), the FlintStatement is constructed. Currently, the FlintStatement does not include the statementContext

I think a better idea is to refactor the JobOperator, to not taking fields from FlintStatement

2025-02-05 09:44 UTC, noCharger commented on spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
> +    val sessionManager = instantiateSessionManager(sparkSession, Some(resultIndex))
can we leverage https://github.com/opensearch-project/opensearch-spark/blob/98579e11c8b9ec0b2c24eeaef8a05fc90d7162e8/spark-sql-application/src/main/scala/org/apache/spark/sql/SingleStatementExecutionManagerImpl.scala which already takes result index?

2025-02-10 17:16 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
> +      if (!throwableHandler.hasException && isStreamingOrBatch) {
Ack, will wrap the monitor logic only for streaming queries

2025-02-10 17:17 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
> +            val jobType = spark.conf.get(FlintSparkConf.JOB_TYPE.key, FlintJobType.BATCH)
This requires bunch of changes on the Client and API. This will increase the scope of this PR. Will take this up in followup PR

2025-02-10 17:17 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
> +}
Ack

2025-02-10 17:31 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
> +    val sessionManager = instantiateSessionManager(sparkSession, Some(resultIndex))
Adding this might increase the scope of this PR. I think we can go ahead with the current approach. We can pick this change later

2025-02-10 17:36 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
> +  val segmentName = getSegmentName(sparkSession)
ack

2025-02-10 17:37 UTC, saranrajnk commented on spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
> +    statementContext: Map[String, Any] = Map.empty[String, Any])
Ack

2025-02-10 18:25 UTC, YANG-DB approved these changes

2025-02-11 00:46 UTC, noCharger reviewed
Everything looks good to me, besides adding session manager to flintjob. One design tenant for interfaces is to make the sink agnostic. I would prefer using SingleStatementExecutionManagerImpl.scala in this refactor to decouple result index and session manager. But since there's already 2 approvals, feel free to merge it.

2025-02-11 16:51 UTC, saranrajnk commented
> Everything looks good to me, besides adding session manager to flintjob. One design tenant for interfaces is to make the sink agnostic. I would prefer using SingleStatementExecutionManagerImpl.scala in this refactor to decouple result index and session manager. But since there's already 2 approvals, feel free to merge it.

I don't have permissions to merge. Can someone merge please?

2025-02-12 22:23 UTC, noCharger commented
> > Everything looks good to me, besides adding session manager to flintjob. One design tenant for interfaces is to make the sink agnostic. I would prefer using SingleStatementExecutionManagerImpl.scala in this refactor to decouple result index and session manager. But since there's already 2 approvals, feel free to merge it.
> 
> I don't have permissions to merge. Can someone merge please?

Let's create a issue for the fast follow up and linked here.

2025-02-13 04:44 UTC, saranrajnk commented
> > > Everything looks good to me, besides adding session manager to flintjob. One design tenant for interfaces is to make the sink agnostic. I would prefer using SingleStatementExecutionManagerImpl.scala in this refactor to decouple result index and session manager. But since there's already 2 approvals, feel free to merge it.
> > 
> > 
> > I don't have permissions to merge. Can someone merge please?
> 
> Let's create a issue for the fast follow up and linked here.

Created an issue - https://github.com/opensearch-project/opensearch-spark/issues/1050

2025-02-13 16:35 UTC, merged